// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Plaid.OpenApiClient.Watchlist_screening.Entity.Create;
using Soenneker.Plaid.OpenApiClient.Watchlist_screening.Entity.Get;
using Soenneker.Plaid.OpenApiClient.Watchlist_screening.Entity.History;
using Soenneker.Plaid.OpenApiClient.Watchlist_screening.Entity.Hit;
using Soenneker.Plaid.OpenApiClient.Watchlist_screening.Entity.List;
using Soenneker.Plaid.OpenApiClient.Watchlist_screening.Entity.Program;
using Soenneker.Plaid.OpenApiClient.Watchlist_screening.Entity.Review;
using Soenneker.Plaid.OpenApiClient.Watchlist_screening.Entity.Update;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Plaid.OpenApiClient.Watchlist_screening.Entity
{
    /// <summary>
    /// Builds and executes requests for operations under \watchlist_screening\entity
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class EntityRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The create property</summary>
        public global::Soenneker.Plaid.OpenApiClient.Watchlist_screening.Entity.Create.CreateRequestBuilder Create
        {
            get => new global::Soenneker.Plaid.OpenApiClient.Watchlist_screening.Entity.Create.CreateRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The getPath property</summary>
        public global::Soenneker.Plaid.OpenApiClient.Watchlist_screening.Entity.Get.GetRequestBuilder GetPath
        {
            get => new global::Soenneker.Plaid.OpenApiClient.Watchlist_screening.Entity.Get.GetRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The history property</summary>
        public global::Soenneker.Plaid.OpenApiClient.Watchlist_screening.Entity.History.HistoryRequestBuilder History
        {
            get => new global::Soenneker.Plaid.OpenApiClient.Watchlist_screening.Entity.History.HistoryRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The hit property</summary>
        public global::Soenneker.Plaid.OpenApiClient.Watchlist_screening.Entity.Hit.HitRequestBuilder Hit
        {
            get => new global::Soenneker.Plaid.OpenApiClient.Watchlist_screening.Entity.Hit.HitRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The list property</summary>
        public global::Soenneker.Plaid.OpenApiClient.Watchlist_screening.Entity.List.ListRequestBuilder List
        {
            get => new global::Soenneker.Plaid.OpenApiClient.Watchlist_screening.Entity.List.ListRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The program property</summary>
        public global::Soenneker.Plaid.OpenApiClient.Watchlist_screening.Entity.Program.ProgramRequestBuilder Program
        {
            get => new global::Soenneker.Plaid.OpenApiClient.Watchlist_screening.Entity.Program.ProgramRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The review property</summary>
        public global::Soenneker.Plaid.OpenApiClient.Watchlist_screening.Entity.Review.ReviewRequestBuilder Review
        {
            get => new global::Soenneker.Plaid.OpenApiClient.Watchlist_screening.Entity.Review.ReviewRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The update property</summary>
        public global::Soenneker.Plaid.OpenApiClient.Watchlist_screening.Entity.Update.UpdateRequestBuilder Update
        {
            get => new global::Soenneker.Plaid.OpenApiClient.Watchlist_screening.Entity.Update.UpdateRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Plaid.OpenApiClient.Watchlist_screening.Entity.EntityRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public EntityRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/watchlist_screening/entity", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Plaid.OpenApiClient.Watchlist_screening.Entity.EntityRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public EntityRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/watchlist_screening/entity", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
