// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Plaid.OpenApiClient.Sandbox.Transfer.Fire_webhook;
using Soenneker.Plaid.OpenApiClient.Sandbox.Transfer.Ledger;
using Soenneker.Plaid.OpenApiClient.Sandbox.Transfer.Refund;
using Soenneker.Plaid.OpenApiClient.Sandbox.Transfer.Repayment;
using Soenneker.Plaid.OpenApiClient.Sandbox.Transfer.Simulate;
using Soenneker.Plaid.OpenApiClient.Sandbox.Transfer.Sweep;
using Soenneker.Plaid.OpenApiClient.Sandbox.Transfer.Test_clock;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Plaid.OpenApiClient.Sandbox.Transfer
{
    /// <summary>
    /// Builds and executes requests for operations under \sandbox\transfer
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class TransferRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The fire_webhook property</summary>
        public global::Soenneker.Plaid.OpenApiClient.Sandbox.Transfer.Fire_webhook.Fire_webhookRequestBuilder Fire_webhook
        {
            get => new global::Soenneker.Plaid.OpenApiClient.Sandbox.Transfer.Fire_webhook.Fire_webhookRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The ledger property</summary>
        public global::Soenneker.Plaid.OpenApiClient.Sandbox.Transfer.Ledger.LedgerRequestBuilder Ledger
        {
            get => new global::Soenneker.Plaid.OpenApiClient.Sandbox.Transfer.Ledger.LedgerRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The refund property</summary>
        public global::Soenneker.Plaid.OpenApiClient.Sandbox.Transfer.Refund.RefundRequestBuilder Refund
        {
            get => new global::Soenneker.Plaid.OpenApiClient.Sandbox.Transfer.Refund.RefundRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The repayment property</summary>
        public global::Soenneker.Plaid.OpenApiClient.Sandbox.Transfer.Repayment.RepaymentRequestBuilder Repayment
        {
            get => new global::Soenneker.Plaid.OpenApiClient.Sandbox.Transfer.Repayment.RepaymentRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The simulate property</summary>
        public global::Soenneker.Plaid.OpenApiClient.Sandbox.Transfer.Simulate.SimulateRequestBuilder Simulate
        {
            get => new global::Soenneker.Plaid.OpenApiClient.Sandbox.Transfer.Simulate.SimulateRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The sweep property</summary>
        public global::Soenneker.Plaid.OpenApiClient.Sandbox.Transfer.Sweep.SweepRequestBuilder Sweep
        {
            get => new global::Soenneker.Plaid.OpenApiClient.Sandbox.Transfer.Sweep.SweepRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The test_clock property</summary>
        public global::Soenneker.Plaid.OpenApiClient.Sandbox.Transfer.Test_clock.Test_clockRequestBuilder Test_clock
        {
            get => new global::Soenneker.Plaid.OpenApiClient.Sandbox.Transfer.Test_clock.Test_clockRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Plaid.OpenApiClient.Sandbox.Transfer.TransferRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TransferRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/sandbox/transfer", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Plaid.OpenApiClient.Sandbox.Transfer.TransferRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TransferRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/sandbox/transfer", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
