// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Plaid.OpenApiClient.Statements.Download;
using Soenneker.Plaid.OpenApiClient.Statements.List;
using Soenneker.Plaid.OpenApiClient.Statements.Refresh;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Plaid.OpenApiClient.Statements
{
    /// <summary>
    /// Builds and executes requests for operations under \statements
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class StatementsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The download property</summary>
        public global::Soenneker.Plaid.OpenApiClient.Statements.Download.DownloadRequestBuilder Download
        {
            get => new global::Soenneker.Plaid.OpenApiClient.Statements.Download.DownloadRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The list property</summary>
        public global::Soenneker.Plaid.OpenApiClient.Statements.List.ListRequestBuilder List
        {
            get => new global::Soenneker.Plaid.OpenApiClient.Statements.List.ListRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The refresh property</summary>
        public global::Soenneker.Plaid.OpenApiClient.Statements.Refresh.RefreshRequestBuilder Refresh
        {
            get => new global::Soenneker.Plaid.OpenApiClient.Statements.Refresh.RefreshRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Plaid.OpenApiClient.Statements.StatementsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public StatementsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/statements", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Plaid.OpenApiClient.Statements.StatementsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public StatementsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/statements", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
