// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Plaid.OpenApiClient.User.Items.Associate;
using Soenneker.Plaid.OpenApiClient.User.Items.Get;
using Soenneker.Plaid.OpenApiClient.User.Items.Remove;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Plaid.OpenApiClient.User.Items
{
    /// <summary>
    /// Builds and executes requests for operations under \user\items
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ItemsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The associate property</summary>
        public global::Soenneker.Plaid.OpenApiClient.User.Items.Associate.AssociateRequestBuilder Associate
        {
            get => new global::Soenneker.Plaid.OpenApiClient.User.Items.Associate.AssociateRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The getPath property</summary>
        public global::Soenneker.Plaid.OpenApiClient.User.Items.Get.GetRequestBuilder GetPath
        {
            get => new global::Soenneker.Plaid.OpenApiClient.User.Items.Get.GetRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The remove property</summary>
        public global::Soenneker.Plaid.OpenApiClient.User.Items.Remove.RemoveRequestBuilder Remove
        {
            get => new global::Soenneker.Plaid.OpenApiClient.User.Items.Remove.RemoveRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Plaid.OpenApiClient.User.Items.ItemsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ItemsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/user/items", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Plaid.OpenApiClient.User.Items.ItemsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ItemsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/user/items", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
