// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Plaid.OpenApiClient.Investments.Auth;
using Soenneker.Plaid.OpenApiClient.Investments.Holdings;
using Soenneker.Plaid.OpenApiClient.Investments.Refresh;
using Soenneker.Plaid.OpenApiClient.Investments.Transactions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Plaid.OpenApiClient.Investments
{
    /// <summary>
    /// Builds and executes requests for operations under \investments
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class InvestmentsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The auth property</summary>
        public global::Soenneker.Plaid.OpenApiClient.Investments.Auth.AuthRequestBuilder Auth
        {
            get => new global::Soenneker.Plaid.OpenApiClient.Investments.Auth.AuthRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The holdings property</summary>
        public global::Soenneker.Plaid.OpenApiClient.Investments.Holdings.HoldingsRequestBuilder Holdings
        {
            get => new global::Soenneker.Plaid.OpenApiClient.Investments.Holdings.HoldingsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The refresh property</summary>
        public global::Soenneker.Plaid.OpenApiClient.Investments.Refresh.RefreshRequestBuilder Refresh
        {
            get => new global::Soenneker.Plaid.OpenApiClient.Investments.Refresh.RefreshRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The transactions property</summary>
        public global::Soenneker.Plaid.OpenApiClient.Investments.Transactions.TransactionsRequestBuilder Transactions
        {
            get => new global::Soenneker.Plaid.OpenApiClient.Investments.Transactions.TransactionsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Plaid.OpenApiClient.Investments.InvestmentsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public InvestmentsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/investments", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Plaid.OpenApiClient.Investments.InvestmentsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public InvestmentsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/investments", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
