// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Plaid.OpenApiClient.Beta.Credit.V1.Bank_employment.Get;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Plaid.OpenApiClient.Beta.Credit.V1.Bank_employment
{
    /// <summary>
    /// Builds and executes requests for operations under \beta\credit\v1\bank_employment
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Bank_employmentRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The getPath property</summary>
        public global::Soenneker.Plaid.OpenApiClient.Beta.Credit.V1.Bank_employment.Get.GetRequestBuilder GetPath
        {
            get => new global::Soenneker.Plaid.OpenApiClient.Beta.Credit.V1.Bank_employment.Get.GetRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Plaid.OpenApiClient.Beta.Credit.V1.Bank_employment.Bank_employmentRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Bank_employmentRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/beta/credit/v1/bank_employment", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Plaid.OpenApiClient.Beta.Credit.V1.Bank_employment.Bank_employmentRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Bank_employmentRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/beta/credit/v1/bank_employment", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
