// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Plaid.OpenApiClient.Idv_classic.Profiles.Id;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Plaid.OpenApiClient.Idv_classic.Profiles
{
    /// <summary>
    /// Builds and executes requests for operations under \idv_classic\profiles
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ProfilesRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The Id property</summary>
        public global::Soenneker.Plaid.OpenApiClient.Idv_classic.Profiles.Id.IdRequestBuilder Id
        {
            get => new global::Soenneker.Plaid.OpenApiClient.Idv_classic.Profiles.Id.IdRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Plaid.OpenApiClient.Idv_classic.Profiles.ProfilesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ProfilesRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/idv_classic/profiles", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Plaid.OpenApiClient.Idv_classic.Profiles.ProfilesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ProfilesRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/idv_classic/profiles", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
