// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Serialization.Form;
using Microsoft.Kiota.Serialization.Json;
using Microsoft.Kiota.Serialization.Multipart;
using Microsoft.Kiota.Serialization.Text;
using Soenneker.Plaid.OpenApiClient.Accounts;
using Soenneker.Plaid.OpenApiClient.Application;
using Soenneker.Plaid.OpenApiClient.Asset_report;
using Soenneker.Plaid.OpenApiClient.Auth;
using Soenneker.Plaid.OpenApiClient.Bank_transfer;
using Soenneker.Plaid.OpenApiClient.Beacon;
using Soenneker.Plaid.OpenApiClient.Beta;
using Soenneker.Plaid.OpenApiClient.Business_verification;
using Soenneker.Plaid.OpenApiClient.Cashflow_report;
using Soenneker.Plaid.OpenApiClient.Categories;
using Soenneker.Plaid.OpenApiClient.Consent;
using Soenneker.Plaid.OpenApiClient.Consumer_report;
using Soenneker.Plaid.OpenApiClient.Cra;
using Soenneker.Plaid.OpenApiClient.Credit;
using Soenneker.Plaid.OpenApiClient.Dashboard_user;
using Soenneker.Plaid.OpenApiClient.Employers;
using Soenneker.Plaid.OpenApiClient.Employment;
using Soenneker.Plaid.OpenApiClient.Fdx;
using Soenneker.Plaid.OpenApiClient.Identity;
using Soenneker.Plaid.OpenApiClient.Identity_verification;
using Soenneker.Plaid.OpenApiClient.Idv_classic;
using Soenneker.Plaid.OpenApiClient.Income;
using Soenneker.Plaid.OpenApiClient.Institutions;
using Soenneker.Plaid.OpenApiClient.Investments;
using Soenneker.Plaid.OpenApiClient.Issues;
using Soenneker.Plaid.OpenApiClient.Item_Escaped;
using Soenneker.Plaid.OpenApiClient.Items;
using Soenneker.Plaid.OpenApiClient.Liabilities;
using Soenneker.Plaid.OpenApiClient.Link;
using Soenneker.Plaid.OpenApiClient.Link_delivery;
using Soenneker.Plaid.OpenApiClient.Network;
using Soenneker.Plaid.OpenApiClient.Network_insights;
using Soenneker.Plaid.OpenApiClient.Oauth;
using Soenneker.Plaid.OpenApiClient.Partner;
using Soenneker.Plaid.OpenApiClient.Payment_initiation;
using Soenneker.Plaid.OpenApiClient.Payment_profile;
using Soenneker.Plaid.OpenApiClient.Processor;
using Soenneker.Plaid.OpenApiClient.Profile;
using Soenneker.Plaid.OpenApiClient.Protect;
using Soenneker.Plaid.OpenApiClient.Sandbox;
using Soenneker.Plaid.OpenApiClient.Session;
using Soenneker.Plaid.OpenApiClient.Signal;
using Soenneker.Plaid.OpenApiClient.Statements;
using Soenneker.Plaid.OpenApiClient.Transactions;
using Soenneker.Plaid.OpenApiClient.Transfer;
using Soenneker.Plaid.OpenApiClient.User;
using Soenneker.Plaid.OpenApiClient.User_account;
using Soenneker.Plaid.OpenApiClient.Wallet;
using Soenneker.Plaid.OpenApiClient.Watchlist_screening;
using Soenneker.Plaid.OpenApiClient.Webhook_verification_key;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Plaid.OpenApiClient
{
    /// <summary>
    /// The main entry point of the SDK, exposes the configuration and the fluent API.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class PlaidOpenApiClient : BaseRequestBuilder
    {
        /// <summary>The accounts property</summary>
        public global::Soenneker.Plaid.OpenApiClient.Accounts.AccountsRequestBuilder Accounts
        {
            get => new global::Soenneker.Plaid.OpenApiClient.Accounts.AccountsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The application property</summary>
        public global::Soenneker.Plaid.OpenApiClient.Application.ApplicationRequestBuilder Application
        {
            get => new global::Soenneker.Plaid.OpenApiClient.Application.ApplicationRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The asset_report property</summary>
        public global::Soenneker.Plaid.OpenApiClient.Asset_report.Asset_reportRequestBuilder Asset_report
        {
            get => new global::Soenneker.Plaid.OpenApiClient.Asset_report.Asset_reportRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The auth property</summary>
        public global::Soenneker.Plaid.OpenApiClient.Auth.AuthRequestBuilder Auth
        {
            get => new global::Soenneker.Plaid.OpenApiClient.Auth.AuthRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The bank_transfer property</summary>
        public global::Soenneker.Plaid.OpenApiClient.Bank_transfer.Bank_transferRequestBuilder Bank_transfer
        {
            get => new global::Soenneker.Plaid.OpenApiClient.Bank_transfer.Bank_transferRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The beacon property</summary>
        public global::Soenneker.Plaid.OpenApiClient.Beacon.BeaconRequestBuilder Beacon
        {
            get => new global::Soenneker.Plaid.OpenApiClient.Beacon.BeaconRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The beta property</summary>
        public global::Soenneker.Plaid.OpenApiClient.Beta.BetaRequestBuilder Beta
        {
            get => new global::Soenneker.Plaid.OpenApiClient.Beta.BetaRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The business_verification property</summary>
        public global::Soenneker.Plaid.OpenApiClient.Business_verification.Business_verificationRequestBuilder Business_verification
        {
            get => new global::Soenneker.Plaid.OpenApiClient.Business_verification.Business_verificationRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The cashflow_report property</summary>
        public global::Soenneker.Plaid.OpenApiClient.Cashflow_report.Cashflow_reportRequestBuilder Cashflow_report
        {
            get => new global::Soenneker.Plaid.OpenApiClient.Cashflow_report.Cashflow_reportRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The categories property</summary>
        public global::Soenneker.Plaid.OpenApiClient.Categories.CategoriesRequestBuilder Categories
        {
            get => new global::Soenneker.Plaid.OpenApiClient.Categories.CategoriesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The consent property</summary>
        public global::Soenneker.Plaid.OpenApiClient.Consent.ConsentRequestBuilder Consent
        {
            get => new global::Soenneker.Plaid.OpenApiClient.Consent.ConsentRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The consumer_report property</summary>
        public global::Soenneker.Plaid.OpenApiClient.Consumer_report.Consumer_reportRequestBuilder Consumer_report
        {
            get => new global::Soenneker.Plaid.OpenApiClient.Consumer_report.Consumer_reportRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The cra property</summary>
        public global::Soenneker.Plaid.OpenApiClient.Cra.CraRequestBuilder Cra
        {
            get => new global::Soenneker.Plaid.OpenApiClient.Cra.CraRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The credit property</summary>
        public global::Soenneker.Plaid.OpenApiClient.Credit.CreditRequestBuilder Credit
        {
            get => new global::Soenneker.Plaid.OpenApiClient.Credit.CreditRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The dashboard_user property</summary>
        public global::Soenneker.Plaid.OpenApiClient.Dashboard_user.Dashboard_userRequestBuilder Dashboard_user
        {
            get => new global::Soenneker.Plaid.OpenApiClient.Dashboard_user.Dashboard_userRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The employers property</summary>
        public global::Soenneker.Plaid.OpenApiClient.Employers.EmployersRequestBuilder Employers
        {
            get => new global::Soenneker.Plaid.OpenApiClient.Employers.EmployersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The employment property</summary>
        public global::Soenneker.Plaid.OpenApiClient.Employment.EmploymentRequestBuilder Employment
        {
            get => new global::Soenneker.Plaid.OpenApiClient.Employment.EmploymentRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The fdx property</summary>
        public global::Soenneker.Plaid.OpenApiClient.Fdx.FdxRequestBuilder Fdx
        {
            get => new global::Soenneker.Plaid.OpenApiClient.Fdx.FdxRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The identity property</summary>
        public global::Soenneker.Plaid.OpenApiClient.Identity.IdentityRequestBuilder Identity
        {
            get => new global::Soenneker.Plaid.OpenApiClient.Identity.IdentityRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The identity_verification property</summary>
        public global::Soenneker.Plaid.OpenApiClient.Identity_verification.Identity_verificationRequestBuilder Identity_verification
        {
            get => new global::Soenneker.Plaid.OpenApiClient.Identity_verification.Identity_verificationRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The idv_classic property</summary>
        public global::Soenneker.Plaid.OpenApiClient.Idv_classic.Idv_classicRequestBuilder Idv_classic
        {
            get => new global::Soenneker.Plaid.OpenApiClient.Idv_classic.Idv_classicRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The income property</summary>
        public global::Soenneker.Plaid.OpenApiClient.Income.IncomeRequestBuilder Income
        {
            get => new global::Soenneker.Plaid.OpenApiClient.Income.IncomeRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The institutions property</summary>
        public global::Soenneker.Plaid.OpenApiClient.Institutions.InstitutionsRequestBuilder Institutions
        {
            get => new global::Soenneker.Plaid.OpenApiClient.Institutions.InstitutionsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The investments property</summary>
        public global::Soenneker.Plaid.OpenApiClient.Investments.InvestmentsRequestBuilder Investments
        {
            get => new global::Soenneker.Plaid.OpenApiClient.Investments.InvestmentsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The issues property</summary>
        public global::Soenneker.Plaid.OpenApiClient.Issues.IssuesRequestBuilder Issues
        {
            get => new global::Soenneker.Plaid.OpenApiClient.Issues.IssuesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The item property</summary>
        public global::Soenneker.Plaid.OpenApiClient.Item_Escaped.Item_EscapedRequestBuilder Item
        {
            get => new global::Soenneker.Plaid.OpenApiClient.Item_Escaped.Item_EscapedRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The items property</summary>
        public global::Soenneker.Plaid.OpenApiClient.Items.ItemsRequestBuilder Items
        {
            get => new global::Soenneker.Plaid.OpenApiClient.Items.ItemsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The liabilities property</summary>
        public global::Soenneker.Plaid.OpenApiClient.Liabilities.LiabilitiesRequestBuilder Liabilities
        {
            get => new global::Soenneker.Plaid.OpenApiClient.Liabilities.LiabilitiesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The link property</summary>
        public global::Soenneker.Plaid.OpenApiClient.Link.LinkRequestBuilder Link
        {
            get => new global::Soenneker.Plaid.OpenApiClient.Link.LinkRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The link_delivery property</summary>
        public global::Soenneker.Plaid.OpenApiClient.Link_delivery.Link_deliveryRequestBuilder Link_delivery
        {
            get => new global::Soenneker.Plaid.OpenApiClient.Link_delivery.Link_deliveryRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The network property</summary>
        public global::Soenneker.Plaid.OpenApiClient.Network.NetworkRequestBuilder Network
        {
            get => new global::Soenneker.Plaid.OpenApiClient.Network.NetworkRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The network_insights property</summary>
        public global::Soenneker.Plaid.OpenApiClient.Network_insights.Network_insightsRequestBuilder Network_insights
        {
            get => new global::Soenneker.Plaid.OpenApiClient.Network_insights.Network_insightsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The oauth property</summary>
        public global::Soenneker.Plaid.OpenApiClient.Oauth.OauthRequestBuilder Oauth
        {
            get => new global::Soenneker.Plaid.OpenApiClient.Oauth.OauthRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The partner property</summary>
        public global::Soenneker.Plaid.OpenApiClient.Partner.PartnerRequestBuilder Partner
        {
            get => new global::Soenneker.Plaid.OpenApiClient.Partner.PartnerRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The payment_initiation property</summary>
        public global::Soenneker.Plaid.OpenApiClient.Payment_initiation.Payment_initiationRequestBuilder Payment_initiation
        {
            get => new global::Soenneker.Plaid.OpenApiClient.Payment_initiation.Payment_initiationRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The payment_profile property</summary>
        public global::Soenneker.Plaid.OpenApiClient.Payment_profile.Payment_profileRequestBuilder Payment_profile
        {
            get => new global::Soenneker.Plaid.OpenApiClient.Payment_profile.Payment_profileRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The processor property</summary>
        public global::Soenneker.Plaid.OpenApiClient.Processor.ProcessorRequestBuilder Processor
        {
            get => new global::Soenneker.Plaid.OpenApiClient.Processor.ProcessorRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The profile property</summary>
        public global::Soenneker.Plaid.OpenApiClient.Profile.ProfileRequestBuilder Profile
        {
            get => new global::Soenneker.Plaid.OpenApiClient.Profile.ProfileRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The protect property</summary>
        public global::Soenneker.Plaid.OpenApiClient.Protect.ProtectRequestBuilder Protect
        {
            get => new global::Soenneker.Plaid.OpenApiClient.Protect.ProtectRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The sandbox property</summary>
        public global::Soenneker.Plaid.OpenApiClient.Sandbox.SandboxRequestBuilder Sandbox
        {
            get => new global::Soenneker.Plaid.OpenApiClient.Sandbox.SandboxRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The session property</summary>
        public global::Soenneker.Plaid.OpenApiClient.Session.SessionRequestBuilder Session
        {
            get => new global::Soenneker.Plaid.OpenApiClient.Session.SessionRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The signal property</summary>
        public global::Soenneker.Plaid.OpenApiClient.Signal.SignalRequestBuilder Signal
        {
            get => new global::Soenneker.Plaid.OpenApiClient.Signal.SignalRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The statements property</summary>
        public global::Soenneker.Plaid.OpenApiClient.Statements.StatementsRequestBuilder Statements
        {
            get => new global::Soenneker.Plaid.OpenApiClient.Statements.StatementsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The transactions property</summary>
        public global::Soenneker.Plaid.OpenApiClient.Transactions.TransactionsRequestBuilder Transactions
        {
            get => new global::Soenneker.Plaid.OpenApiClient.Transactions.TransactionsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The transfer property</summary>
        public global::Soenneker.Plaid.OpenApiClient.Transfer.TransferRequestBuilder Transfer
        {
            get => new global::Soenneker.Plaid.OpenApiClient.Transfer.TransferRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The user property</summary>
        public global::Soenneker.Plaid.OpenApiClient.User.UserRequestBuilder User
        {
            get => new global::Soenneker.Plaid.OpenApiClient.User.UserRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The user_account property</summary>
        public global::Soenneker.Plaid.OpenApiClient.User_account.User_accountRequestBuilder User_account
        {
            get => new global::Soenneker.Plaid.OpenApiClient.User_account.User_accountRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The wallet property</summary>
        public global::Soenneker.Plaid.OpenApiClient.Wallet.WalletRequestBuilder Wallet
        {
            get => new global::Soenneker.Plaid.OpenApiClient.Wallet.WalletRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The watchlist_screening property</summary>
        public global::Soenneker.Plaid.OpenApiClient.Watchlist_screening.Watchlist_screeningRequestBuilder Watchlist_screening
        {
            get => new global::Soenneker.Plaid.OpenApiClient.Watchlist_screening.Watchlist_screeningRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The webhook_verification_key property</summary>
        public global::Soenneker.Plaid.OpenApiClient.Webhook_verification_key.Webhook_verification_keyRequestBuilder Webhook_verification_key
        {
            get => new global::Soenneker.Plaid.OpenApiClient.Webhook_verification_key.Webhook_verification_keyRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Plaid.OpenApiClient.PlaidOpenApiClient"/> and sets the default values.
        /// </summary>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PlaidOpenApiClient(IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}", new Dictionary<string, object>())
        {
            ApiClientBuilder.RegisterDefaultSerializer<JsonSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<TextSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<FormSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<MultipartSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<JsonParseNodeFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<TextParseNodeFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<FormParseNodeFactory>();
            if (string.IsNullOrEmpty(RequestAdapter.BaseUrl))
            {
                RequestAdapter.BaseUrl = "https://production.plaid.com";
            }
            PathParameters.TryAdd("baseurl", RequestAdapter.BaseUrl);
        }
    }
}
#pragma warning restore CS0618
