// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Plaid.OpenApiClient.Processor.Identity.Get;
using Soenneker.Plaid.OpenApiClient.Processor.Identity.Match;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Plaid.OpenApiClient.Processor.Identity
{
    /// <summary>
    /// Builds and executes requests for operations under \processor\identity
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class IdentityRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The getPath property</summary>
        public global::Soenneker.Plaid.OpenApiClient.Processor.Identity.Get.GetRequestBuilder GetPath
        {
            get => new global::Soenneker.Plaid.OpenApiClient.Processor.Identity.Get.GetRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The match property</summary>
        public global::Soenneker.Plaid.OpenApiClient.Processor.Identity.Match.MatchRequestBuilder Match
        {
            get => new global::Soenneker.Plaid.OpenApiClient.Processor.Identity.Match.MatchRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Plaid.OpenApiClient.Processor.Identity.IdentityRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public IdentityRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/processor/identity", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Plaid.OpenApiClient.Processor.Identity.IdentityRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public IdentityRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/processor/identity", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
