// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Plaid.OpenApiClient.Models
{
    /// <summary>
    /// Identity information about an account
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class AccountIdentityDocumentUpload : global::Soenneker.Plaid.OpenApiClient.Models.AccountBase, IParsable
    {
        /// <summary>Data about the documents that were uploaded as proof of account ownership.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Plaid.OpenApiClient.Models.IdentityDocumentUpload>? Documents { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Plaid.OpenApiClient.Models.IdentityDocumentUpload> Documents { get; set; }
#endif
        /// <summary>Data returned by the financial institution about the account owner or owners. Only returned by Identity or Assets endpoints. For business accounts, the name reported may be either the name of the individual or the name of the business, depending on the institution; detecting whether the linked account is a business account is not currently supported. Multiple owners on a single account will be represented in the same `owner` object, not in multiple owner objects within the array. In API versions 2018-05-22 and earlier, the `owners` object is not returned, and instead identity information is returned in the top level `identity` object. For more details, see [Plaid API versioning](https://plaid.com/docs/api/versioning/#version-2019-05-29)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Plaid.OpenApiClient.Models.Owner>? Owners { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Plaid.OpenApiClient.Models.Owner> Owners { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Plaid.OpenApiClient.Models.AccountIdentityDocumentUpload"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static new global::Soenneker.Plaid.OpenApiClient.Models.AccountIdentityDocumentUpload CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Plaid.OpenApiClient.Models.AccountIdentityDocumentUpload();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public override IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>(base.GetFieldDeserializers())
            {
                { "documents", n => { Documents = n.GetCollectionOfObjectValues<global::Soenneker.Plaid.OpenApiClient.Models.IdentityDocumentUpload>(global::Soenneker.Plaid.OpenApiClient.Models.IdentityDocumentUpload.CreateFromDiscriminatorValue)?.AsList(); } },
                { "owners", n => { Owners = n.GetCollectionOfObjectValues<global::Soenneker.Plaid.OpenApiClient.Models.Owner>(global::Soenneker.Plaid.OpenApiClient.Models.Owner.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public override void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            base.Serialize(writer);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Plaid.OpenApiClient.Models.IdentityDocumentUpload>("documents", Documents);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Plaid.OpenApiClient.Models.Owner>("owners", Owners);
        }
    }
}
#pragma warning restore CS0618
