// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Plaid.OpenApiClient.Models
{
    /// <summary>
    /// The `account_filters` specified in the original call to `/link/token/create`.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class AccountFiltersResponse : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>A filter to apply to `credit`-type accounts</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Plaid.OpenApiClient.Models.CreditFilter? Credit { get; set; }
#nullable restore
#else
        public global::Soenneker.Plaid.OpenApiClient.Models.CreditFilter Credit { get; set; }
#endif
        /// <summary>A filter to apply to `depository`-type accounts</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Plaid.OpenApiClient.Models.DepositoryFilter? Depository { get; set; }
#nullable restore
#else
        public global::Soenneker.Plaid.OpenApiClient.Models.DepositoryFilter Depository { get; set; }
#endif
        /// <summary>A filter to apply to `investment`-type accounts (or `brokerage`-type accounts for API versions 2018-05-22 and earlier).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Plaid.OpenApiClient.Models.InvestmentFilter? Investment { get; set; }
#nullable restore
#else
        public global::Soenneker.Plaid.OpenApiClient.Models.InvestmentFilter Investment { get; set; }
#endif
        /// <summary>A filter to apply to `loan`-type accounts</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Plaid.OpenApiClient.Models.LoanFilter? Loan { get; set; }
#nullable restore
#else
        public global::Soenneker.Plaid.OpenApiClient.Models.LoanFilter Loan { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Plaid.OpenApiClient.Models.AccountFiltersResponse"/> and sets the default values.
        /// </summary>
        public AccountFiltersResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Plaid.OpenApiClient.Models.AccountFiltersResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Plaid.OpenApiClient.Models.AccountFiltersResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Plaid.OpenApiClient.Models.AccountFiltersResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "credit", n => { Credit = n.GetObjectValue<global::Soenneker.Plaid.OpenApiClient.Models.CreditFilter>(global::Soenneker.Plaid.OpenApiClient.Models.CreditFilter.CreateFromDiscriminatorValue); } },
                { "depository", n => { Depository = n.GetObjectValue<global::Soenneker.Plaid.OpenApiClient.Models.DepositoryFilter>(global::Soenneker.Plaid.OpenApiClient.Models.DepositoryFilter.CreateFromDiscriminatorValue); } },
                { "investment", n => { Investment = n.GetObjectValue<global::Soenneker.Plaid.OpenApiClient.Models.InvestmentFilter>(global::Soenneker.Plaid.OpenApiClient.Models.InvestmentFilter.CreateFromDiscriminatorValue); } },
                { "loan", n => { Loan = n.GetObjectValue<global::Soenneker.Plaid.OpenApiClient.Models.LoanFilter>(global::Soenneker.Plaid.OpenApiClient.Models.LoanFilter.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Plaid.OpenApiClient.Models.CreditFilter>("credit", Credit);
            writer.WriteObjectValue<global::Soenneker.Plaid.OpenApiClient.Models.DepositoryFilter>("depository", Depository);
            writer.WriteObjectValue<global::Soenneker.Plaid.OpenApiClient.Models.InvestmentFilter>("investment", Investment);
            writer.WriteObjectValue<global::Soenneker.Plaid.OpenApiClient.Models.LoanFilter>("loan", Loan);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
