// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Plaid.OpenApiClient.Models
{
    /// <summary>
    /// Insights from performing database verification for the account. Only returned for Auth Items using Database Auth.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class AccountVerificationInsights : IAdditionalDataHolder, IParsable
    {
        /// <summary>Indicator of account number format validity for institution.`valid`: indicates that the account number has a correct format for the institution.`invalid`: indicates that the account number has an incorrect format for the institution.`unknown`: indicates that there was not enough information to determine whether the format is correct for the institution.</summary>
        public global::Soenneker.Plaid.OpenApiClient.Models.AccountVerificationInsightsAccountNumberFormat? AccountNumberFormat { get; set; }
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Indicates the score of the name match between the given name provided during database verification (available in the [`verification_name`](https://plaid.com/docs/api/products/auth/#auth-get-response-accounts-verification-name) field if using standard Database Auth, or provided in the request if using `/auth/verify`) and matched Plaid network accounts. If defined, will be a value between 0 and 100. Will be undefined if name matching was not enabled for the database verification session or if there were no eligible Plaid network matches to compare the given name with.</summary>
        public int? NameMatchScore { get; set; }
        /// <summary>Status information about the account and routing number in the Plaid network.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Plaid.OpenApiClient.Models.AccountVerificationInsightsNetworkStatus? NetworkStatus { get; set; }
#nullable restore
#else
        public global::Soenneker.Plaid.OpenApiClient.Models.AccountVerificationInsightsNetworkStatus NetworkStatus { get; set; }
#endif
        /// <summary>Information about known ACH returns for the account and routing number.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Plaid.OpenApiClient.Models.AccountVerificationInsightsPreviousReturns? PreviousReturns { get; set; }
#nullable restore
#else
        public global::Soenneker.Plaid.OpenApiClient.Models.AccountVerificationInsightsPreviousReturns PreviousReturns { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Plaid.OpenApiClient.Models.AccountVerificationInsights"/> and sets the default values.
        /// </summary>
        public AccountVerificationInsights()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Plaid.OpenApiClient.Models.AccountVerificationInsights"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Plaid.OpenApiClient.Models.AccountVerificationInsights CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Plaid.OpenApiClient.Models.AccountVerificationInsights();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "account_number_format", n => { AccountNumberFormat = n.GetEnumValue<global::Soenneker.Plaid.OpenApiClient.Models.AccountVerificationInsightsAccountNumberFormat>(); } },
                { "name_match_score", n => { NameMatchScore = n.GetIntValue(); } },
                { "network_status", n => { NetworkStatus = n.GetObjectValue<global::Soenneker.Plaid.OpenApiClient.Models.AccountVerificationInsightsNetworkStatus>(global::Soenneker.Plaid.OpenApiClient.Models.AccountVerificationInsightsNetworkStatus.CreateFromDiscriminatorValue); } },
                { "previous_returns", n => { PreviousReturns = n.GetObjectValue<global::Soenneker.Plaid.OpenApiClient.Models.AccountVerificationInsightsPreviousReturns>(global::Soenneker.Plaid.OpenApiClient.Models.AccountVerificationInsightsPreviousReturns.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteEnumValue<global::Soenneker.Plaid.OpenApiClient.Models.AccountVerificationInsightsAccountNumberFormat>("account_number_format", AccountNumberFormat);
            writer.WriteIntValue("name_match_score", NameMatchScore);
            writer.WriteObjectValue<global::Soenneker.Plaid.OpenApiClient.Models.AccountVerificationInsightsNetworkStatus>("network_status", NetworkStatus);
            writer.WriteObjectValue<global::Soenneker.Plaid.OpenApiClient.Models.AccountVerificationInsightsPreviousReturns>("previous_returns", PreviousReturns);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
