// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Plaid.OpenApiClient.Models
{
    /// <summary>Enum representing the state of the action/activity.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ActionState
    {
        [EnumMember(Value = "UNKNOWN")]
        #pragma warning disable CS1591
        UNKNOWN,
        #pragma warning restore CS1591
        [EnumMember(Value = "ATTEMPT")]
        #pragma warning disable CS1591
        ATTEMPT,
        #pragma warning restore CS1591
        [EnumMember(Value = "SUCCESS")]
        #pragma warning disable CS1591
        SUCCESS,
        #pragma warning restore CS1591
        [EnumMember(Value = "FAILURE")]
        #pragma warning disable CS1591
        FAILURE,
        #pragma warning restore CS1591
        [EnumMember(Value = "SKIPPED")]
        #pragma warning disable CS1591
        SKIPPED,
        #pragma warning restore CS1591
    }
}
