// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Plaid.OpenApiClient.Models
{
    /// <summary>A value from a MISMO prescribed list that specifies financial assets in a mortgage loan transaction. Assets may be either liquid or fixed and are associated with a corresponding asset amount.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum AssetType
    {
        [EnumMember(Value = "CheckingAccount")]
        #pragma warning disable CS1591
        CheckingAccount,
        #pragma warning restore CS1591
        [EnumMember(Value = "SavingsAccount")]
        #pragma warning disable CS1591
        SavingsAccount,
        #pragma warning restore CS1591
        [EnumMember(Value = "Investment")]
        #pragma warning disable CS1591
        Investment,
        #pragma warning restore CS1591
        [EnumMember(Value = "MoneyMarketFund")]
        #pragma warning disable CS1591
        MoneyMarketFund,
        #pragma warning restore CS1591
        [EnumMember(Value = "Other")]
        #pragma warning disable CS1591
        Other,
        #pragma warning restore CS1591
    }
}
