// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Plaid.OpenApiClient.Models
{
    /// <summary>
    /// A transaction within an investment account.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class BaseReportInvestmentTransaction : IAdditionalDataHolder, IParsable
    {
        /// <summary>The `account_id` of the account against which this transaction posted.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AccountId { get; set; }
#nullable restore
#else
        public string AccountId { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The complete value of the transaction. Positive values when cash is debited, e.g. purchases of stock; negative values when cash is credited, e.g. sales of stock. Treatment remains the same for cash-only movements unassociated with securities.</summary>
        public double? Amount { get; set; }
        /// <summary>The [ISO 8601](https://wikipedia.org/wiki/ISO_8601) posting date for the transaction.</summary>
        public Date? Date { get; set; }
        /// <summary>The combined value of all fees applied to this transaction</summary>
        public double? Fees { get; set; }
        /// <summary>The ID of the Investment transaction, unique across all Plaid transactions. Like all Plaid identifiers, the `investment_transaction_id` is case sensitive.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? InvestmentTransactionId { get; set; }
#nullable restore
#else
        public string InvestmentTransactionId { get; set; }
#endif
        /// <summary>The ISO-4217 currency code of the transaction. Always `null` if `unofficial_currency_code` is non-`null`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? IsoCurrencyCode { get; set; }
#nullable restore
#else
        public string IsoCurrencyCode { get; set; }
#endif
        /// <summary>The institution’s description of the transaction.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The price of the security at which this transaction occurred.</summary>
        public double? Price { get; set; }
        /// <summary>The number of units of the security involved in this transaction. Positive for buy transactions; negative for sell transactions.</summary>
        public double? Quantity { get; set; }
        /// <summary>The `security_id` to which this transaction is related.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SecurityId { get; set; }
#nullable restore
#else
        public string SecurityId { get; set; }
#endif
        /// <summary>For descriptions of possible transaction types and subtypes, see the [Investment transaction types schema](https://plaid.com/docs/api/accounts/#investment-transaction-types-schema).</summary>
        public global::Soenneker.Plaid.OpenApiClient.Models.InvestmentTransactionSubtype? Subtype { get; set; }
        /// <summary>Value is one of the following:`buy`: Buying an investment`sell`: Selling an investment`cancel`: A cancellation of a pending transaction`cash`: Activity that modifies a cash position`fee`: A fee on the account`transfer`: Activity which modifies a position, but not through buy/sell activity e.g. options exercise, portfolio transferFor descriptions of possible transaction types and subtypes, see the [Investment transaction types schema](https://plaid.com/docs/api/accounts/#investment-transaction-types-schema).</summary>
        public global::Soenneker.Plaid.OpenApiClient.Models.InvestmentTransactionType? Type { get; set; }
        /// <summary>The unofficial currency code associated with the holding. Always `null` if `iso_currency_code` is non-`null`. Unofficial currency codes are used for currencies that do not have official ISO currency codes, such as cryptocurrencies and the currencies of certain countries.See the [currency code schema](https://plaid.com/docs/api/accounts#currency-code-schema) for a full listing of supported `iso_currency_code`s.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UnofficialCurrencyCode { get; set; }
#nullable restore
#else
        public string UnofficialCurrencyCode { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Plaid.OpenApiClient.Models.BaseReportInvestmentTransaction"/> and sets the default values.
        /// </summary>
        public BaseReportInvestmentTransaction()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Plaid.OpenApiClient.Models.BaseReportInvestmentTransaction"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Plaid.OpenApiClient.Models.BaseReportInvestmentTransaction CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Plaid.OpenApiClient.Models.BaseReportInvestmentTransaction();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "account_id", n => { AccountId = n.GetStringValue(); } },
                { "amount", n => { Amount = n.GetDoubleValue(); } },
                { "date", n => { Date = n.GetDateValue(); } },
                { "fees", n => { Fees = n.GetDoubleValue(); } },
                { "investment_transaction_id", n => { InvestmentTransactionId = n.GetStringValue(); } },
                { "iso_currency_code", n => { IsoCurrencyCode = n.GetStringValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "price", n => { Price = n.GetDoubleValue(); } },
                { "quantity", n => { Quantity = n.GetDoubleValue(); } },
                { "security_id", n => { SecurityId = n.GetStringValue(); } },
                { "subtype", n => { Subtype = n.GetEnumValue<global::Soenneker.Plaid.OpenApiClient.Models.InvestmentTransactionSubtype>(); } },
                { "type", n => { Type = n.GetEnumValue<global::Soenneker.Plaid.OpenApiClient.Models.InvestmentTransactionType>(); } },
                { "unofficial_currency_code", n => { UnofficialCurrencyCode = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("account_id", AccountId);
            writer.WriteDoubleValue("amount", Amount);
            writer.WriteDateValue("date", Date);
            writer.WriteDoubleValue("fees", Fees);
            writer.WriteStringValue("investment_transaction_id", InvestmentTransactionId);
            writer.WriteStringValue("iso_currency_code", IsoCurrencyCode);
            writer.WriteStringValue("name", Name);
            writer.WriteDoubleValue("price", Price);
            writer.WriteDoubleValue("quantity", Quantity);
            writer.WriteStringValue("security_id", SecurityId);
            writer.WriteEnumValue<global::Soenneker.Plaid.OpenApiClient.Models.InvestmentTransactionSubtype>("subtype", Subtype);
            writer.WriteEnumValue<global::Soenneker.Plaid.OpenApiClient.Models.InvestmentTransactionType>("type", Type);
            writer.WriteStringValue("unofficial_currency_code", UnofficialCurrencyCode);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
