// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Plaid.OpenApiClient.Models
{
    /// <summary>
    /// Investment security associated with the account.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class BaseReportInvestmentSecurity : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>9-character CUSIP, an identifier assigned to North American securities. A verified CUSIP Global Services license is required to receive this data. This field will be null by default for new customers, and null for existing customers starting March 12, 2024. If you would like access to this field, please start the verification process [here](https://docs.google.com/forms/d/e/1FAIpQLSd9asHEYEfmf8fxJTHZTAfAzW4dugsnSu-HS2J51f1mxwd6Sw/viewform).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Cusip { get; set; }
#nullable restore
#else
        public string Cusip { get; set; }
#endif
        /// <summary>If `institution_security_id` is present, this field indicates the Plaid `institution_id` of the institution to whom the identifier belongs.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? InstitutionId { get; set; }
#nullable restore
#else
        public string InstitutionId { get; set; }
#endif
        /// <summary>An identifier given to the security by the institution.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? InstitutionSecurityId { get; set; }
#nullable restore
#else
        public string InstitutionSecurityId { get; set; }
#endif
        /// <summary>12-character ISIN, a globally unique securities identifier. A verified CUSIP Global Services license is required to receive this data. This field will be null by default for new customers, and null for existing customers starting March 12, 2024. If you would like access to this field, please start the verification process [here](https://docs.google.com/forms/d/e/1FAIpQLSd9asHEYEfmf8fxJTHZTAfAzW4dugsnSu-HS2J51f1mxwd6Sw/viewform).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Isin { get; set; }
#nullable restore
#else
        public string Isin { get; set; }
#endif
        /// <summary>A descriptive name for the security, suitable for display.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>A unique, Plaid-specific identifier for the security, used to associate securities with holdings. Like all Plaid identifiers, the `security_id` is case sensitive. The `security_id` may change if inherent details of the security change due to a corporate action, for example, in the event of a ticker symbol change or CUSIP change.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SecurityId { get; set; }
#nullable restore
#else
        public string SecurityId { get; set; }
#endif
        /// <summary>The security’s trading symbol for publicly traded securities, and otherwise a short identifier if available.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TickerSymbol { get; set; }
#nullable restore
#else
        public string TickerSymbol { get; set; }
#endif
        /// <summary>The security type of the holding. Valid security types are:`cash`: Cash, currency, and money market funds`cryptocurrency`: Digital or virtual currencies`derivative`: Options, warrants, and other derivative instruments`equity`: Domestic and foreign equities`etf`: Multi-asset exchange-traded investment funds`fixed income`: Bonds and certificates of deposit (CDs)`loan`: Loans and loan receivables`mutual fund`: Open- and closed-end vehicles pooling funds of multiple investors`other`: Unknown or other investment types</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Type { get; set; }
#nullable restore
#else
        public string Type { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Plaid.OpenApiClient.Models.BaseReportInvestmentSecurity"/> and sets the default values.
        /// </summary>
        public BaseReportInvestmentSecurity()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Plaid.OpenApiClient.Models.BaseReportInvestmentSecurity"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Plaid.OpenApiClient.Models.BaseReportInvestmentSecurity CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Plaid.OpenApiClient.Models.BaseReportInvestmentSecurity();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "cusip", n => { Cusip = n.GetStringValue(); } },
                { "institution_id", n => { InstitutionId = n.GetStringValue(); } },
                { "institution_security_id", n => { InstitutionSecurityId = n.GetStringValue(); } },
                { "isin", n => { Isin = n.GetStringValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "security_id", n => { SecurityId = n.GetStringValue(); } },
                { "ticker_symbol", n => { TickerSymbol = n.GetStringValue(); } },
                { "type", n => { Type = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("cusip", Cusip);
            writer.WriteStringValue("institution_id", InstitutionId);
            writer.WriteStringValue("institution_security_id", InstitutionSecurityId);
            writer.WriteStringValue("isin", Isin);
            writer.WriteStringValue("name", Name);
            writer.WriteStringValue("security_id", SecurityId);
            writer.WriteStringValue("ticker_symbol", TickerSymbol);
            writer.WriteStringValue("type", Type);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
