// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Plaid.OpenApiClient.Models
{
    /// <summary>
    /// Results from the business risk assessment check
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class BusinessRiskCheck : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Nullable industry prediction details.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Plaid.OpenApiClient.Models.BusinessIndustryPredictionNullable? IndustryPrediction { get; set; }
#nullable restore
#else
        public global::Soenneker.Plaid.OpenApiClient.Models.BusinessIndustryPredictionNullable IndustryPrediction { get; set; }
#endif
        /// <summary>A score from 0 to 100 indicating the risk assessment for the business</summary>
        public int? Score { get; set; }
        /// <summary>Status of the business risk assessment check</summary>
        public global::Soenneker.Plaid.OpenApiClient.Models.BusinessVerificationStatus__RiskCheck? Status { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Plaid.OpenApiClient.Models.BusinessRiskCheck"/> and sets the default values.
        /// </summary>
        public BusinessRiskCheck()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Plaid.OpenApiClient.Models.BusinessRiskCheck"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Plaid.OpenApiClient.Models.BusinessRiskCheck CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Plaid.OpenApiClient.Models.BusinessRiskCheck();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "industry_prediction", n => { IndustryPrediction = n.GetObjectValue<global::Soenneker.Plaid.OpenApiClient.Models.BusinessIndustryPredictionNullable>(global::Soenneker.Plaid.OpenApiClient.Models.BusinessIndustryPredictionNullable.CreateFromDiscriminatorValue); } },
                { "score", n => { Score = n.GetIntValue(); } },
                { "status", n => { Status = n.GetEnumValue<global::Soenneker.Plaid.OpenApiClient.Models.BusinessVerificationStatus__RiskCheck>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Plaid.OpenApiClient.Models.BusinessIndustryPredictionNullable>("industry_prediction", IndustryPrediction);
            writer.WriteIntValue("score", Score);
            writer.WriteEnumValue<global::Soenneker.Plaid.OpenApiClient.Models.BusinessVerificationStatus__RiskCheck>("status", Status);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
