// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Plaid.OpenApiClient.Models
{
    /// <summary>
    /// Summary for income across all income sources and items (max history of 730 days).
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CraBankIncomeSummary : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The latest date in which all income sources identified by Plaid appear in the user&apos;s account.The date will be returned in an ISO 8601 format (YYYY-MM-DD).</summary>
        public Date? EndDate { get; set; }
        /// <summary>The predicted average annual income amount for the income source(s).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Plaid.OpenApiClient.Models.CreditAmountWithCurrency>? ForecastedAnnualIncome { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Plaid.OpenApiClient.Models.CreditAmountWithCurrency> ForecastedAnnualIncome { get; set; }
#endif
        /// <summary>The predicted average monthly income amount for the income source(s).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Plaid.OpenApiClient.Models.CreditAmountWithCurrency>? ForecastedAverageMonthlyIncome { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Plaid.OpenApiClient.Models.CreditAmountWithCurrency> ForecastedAverageMonthlyIncome { get; set; }
#endif
        /// <summary>An estimate of the annual gross income for the income source, calculated by multiplying the `historical_average_monthly_gross_income` by 12.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Plaid.OpenApiClient.Models.CreditAmountWithCurrency>? HistoricalAnnualGrossIncome { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Plaid.OpenApiClient.Models.CreditAmountWithCurrency> HistoricalAnnualGrossIncome { get; set; }
#endif
        /// <summary>An estimate of the annual net income for the income source, calculated by multiplying the `historical_average_monthly_income` by 12.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Plaid.OpenApiClient.Models.CreditAmountWithCurrency>? HistoricalAnnualIncome { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Plaid.OpenApiClient.Models.CreditAmountWithCurrency> HistoricalAnnualIncome { get; set; }
#endif
        /// <summary>An estimate of the average gross monthly income based on the historical net amount and income category for the income source(s). The average monthly income is calculated based on the lifetime of the income stream, rather than the entire historical period included in the scope of the report.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Plaid.OpenApiClient.Models.CreditAmountWithCurrency>? HistoricalAverageMonthlyGrossIncome { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Plaid.OpenApiClient.Models.CreditAmountWithCurrency> HistoricalAverageMonthlyGrossIncome { get; set; }
#endif
        /// <summary>The average monthly income amount estimated based on the historical data for the income source(s). The average monthly income is calculated based on the lifetime of the income stream, rather than the entire historical period included in the scope of the report.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Plaid.OpenApiClient.Models.CreditAmountWithCurrency>? HistoricalAverageMonthlyIncome { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Plaid.OpenApiClient.Models.CreditAmountWithCurrency> HistoricalAverageMonthlyIncome { get; set; }
#endif
        /// <summary>The historical_summary property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Plaid.OpenApiClient.Models.CraBankIncomeHistoricalSummary>? HistoricalSummary { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Plaid.OpenApiClient.Models.CraBankIncomeHistoricalSummary> HistoricalSummary { get; set; }
#endif
        /// <summary>Number of income categories per end user.</summary>
        public int? IncomeCategoriesCount { get; set; }
        /// <summary>Number of income sources per end user.</summary>
        public int? IncomeSourcesCount { get; set; }
        /// <summary>Number of income transactions per end user.</summary>
        public int? IncomeTransactionsCount { get; set; }
        /// <summary>The earliest date within the days requested in which all income sources identified by Plaid appear in a user&apos;s account.The date will be returned in an ISO 8601 format (YYYY-MM-DD).</summary>
        public Date? StartDate { get; set; }
        /// <summary>Total amount of earnings across all the income sources in the end user&apos;s Items for the days requested by the client.This can contain multiple amounts, with each amount denominated in one unique currency.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Plaid.OpenApiClient.Models.CreditAmountWithCurrency>? TotalAmounts { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Plaid.OpenApiClient.Models.CreditAmountWithCurrency> TotalAmounts { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Plaid.OpenApiClient.Models.CraBankIncomeSummary"/> and sets the default values.
        /// </summary>
        public CraBankIncomeSummary()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Plaid.OpenApiClient.Models.CraBankIncomeSummary"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Plaid.OpenApiClient.Models.CraBankIncomeSummary CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Plaid.OpenApiClient.Models.CraBankIncomeSummary();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "end_date", n => { EndDate = n.GetDateValue(); } },
                { "forecasted_annual_income", n => { ForecastedAnnualIncome = n.GetCollectionOfObjectValues<global::Soenneker.Plaid.OpenApiClient.Models.CreditAmountWithCurrency>(global::Soenneker.Plaid.OpenApiClient.Models.CreditAmountWithCurrency.CreateFromDiscriminatorValue)?.AsList(); } },
                { "forecasted_average_monthly_income", n => { ForecastedAverageMonthlyIncome = n.GetCollectionOfObjectValues<global::Soenneker.Plaid.OpenApiClient.Models.CreditAmountWithCurrency>(global::Soenneker.Plaid.OpenApiClient.Models.CreditAmountWithCurrency.CreateFromDiscriminatorValue)?.AsList(); } },
                { "historical_annual_gross_income", n => { HistoricalAnnualGrossIncome = n.GetCollectionOfObjectValues<global::Soenneker.Plaid.OpenApiClient.Models.CreditAmountWithCurrency>(global::Soenneker.Plaid.OpenApiClient.Models.CreditAmountWithCurrency.CreateFromDiscriminatorValue)?.AsList(); } },
                { "historical_annual_income", n => { HistoricalAnnualIncome = n.GetCollectionOfObjectValues<global::Soenneker.Plaid.OpenApiClient.Models.CreditAmountWithCurrency>(global::Soenneker.Plaid.OpenApiClient.Models.CreditAmountWithCurrency.CreateFromDiscriminatorValue)?.AsList(); } },
                { "historical_average_monthly_gross_income", n => { HistoricalAverageMonthlyGrossIncome = n.GetCollectionOfObjectValues<global::Soenneker.Plaid.OpenApiClient.Models.CreditAmountWithCurrency>(global::Soenneker.Plaid.OpenApiClient.Models.CreditAmountWithCurrency.CreateFromDiscriminatorValue)?.AsList(); } },
                { "historical_average_monthly_income", n => { HistoricalAverageMonthlyIncome = n.GetCollectionOfObjectValues<global::Soenneker.Plaid.OpenApiClient.Models.CreditAmountWithCurrency>(global::Soenneker.Plaid.OpenApiClient.Models.CreditAmountWithCurrency.CreateFromDiscriminatorValue)?.AsList(); } },
                { "historical_summary", n => { HistoricalSummary = n.GetCollectionOfObjectValues<global::Soenneker.Plaid.OpenApiClient.Models.CraBankIncomeHistoricalSummary>(global::Soenneker.Plaid.OpenApiClient.Models.CraBankIncomeHistoricalSummary.CreateFromDiscriminatorValue)?.AsList(); } },
                { "income_categories_count", n => { IncomeCategoriesCount = n.GetIntValue(); } },
                { "income_sources_count", n => { IncomeSourcesCount = n.GetIntValue(); } },
                { "income_transactions_count", n => { IncomeTransactionsCount = n.GetIntValue(); } },
                { "start_date", n => { StartDate = n.GetDateValue(); } },
                { "total_amounts", n => { TotalAmounts = n.GetCollectionOfObjectValues<global::Soenneker.Plaid.OpenApiClient.Models.CreditAmountWithCurrency>(global::Soenneker.Plaid.OpenApiClient.Models.CreditAmountWithCurrency.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDateValue("end_date", EndDate);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Plaid.OpenApiClient.Models.CreditAmountWithCurrency>("forecasted_annual_income", ForecastedAnnualIncome);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Plaid.OpenApiClient.Models.CreditAmountWithCurrency>("forecasted_average_monthly_income", ForecastedAverageMonthlyIncome);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Plaid.OpenApiClient.Models.CreditAmountWithCurrency>("historical_annual_gross_income", HistoricalAnnualGrossIncome);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Plaid.OpenApiClient.Models.CreditAmountWithCurrency>("historical_annual_income", HistoricalAnnualIncome);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Plaid.OpenApiClient.Models.CreditAmountWithCurrency>("historical_average_monthly_gross_income", HistoricalAverageMonthlyGrossIncome);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Plaid.OpenApiClient.Models.CreditAmountWithCurrency>("historical_average_monthly_income", HistoricalAverageMonthlyIncome);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Plaid.OpenApiClient.Models.CraBankIncomeHistoricalSummary>("historical_summary", HistoricalSummary);
            writer.WriteIntValue("income_categories_count", IncomeCategoriesCount);
            writer.WriteIntValue("income_sources_count", IncomeSourcesCount);
            writer.WriteIntValue("income_transactions_count", IncomeTransactionsCount);
            writer.WriteDateValue("start_date", StartDate);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Plaid.OpenApiClient.Models.CreditAmountWithCurrency>("total_amounts", TotalAmounts);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
