// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Plaid.OpenApiClient.Models
{
    /// <summary>The version of the credit profile report to retrieve.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum CraCreditProfileReportVersion
    {
        [EnumMember(Value = "v1")]
        #pragma warning disable CS1591
        V1,
        #pragma warning restore CS1591
    }
}
