// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Plaid.OpenApiClient.Models
{
    /// <summary>
    /// Defines configuration options to generate Income Insights.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CraCheckReportIncomeInsightsGetOptions : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Filters the returned income streams based on the specified income categories. If no filters are requested, streams from the following default set of categories are returned:- `EARNED_INCOME.*` (`EARNED_INCOME.SALARY`, `EARNED_INCOME.GIG_ECONOMY`, `EARNED_INCOME.SELF_EMPLOYED`)- `BENEFITS.DISABILITY`- `RETIREMENT.*` (`RETIREMENT.GOVERNMENT_DERIVED`, `RETIREMENT.PRIVATE_RETIREMENT`, `RETIREMENT.PLAN_DISTRIBUTION`)The final list of income categories is generated by adding the `included_categories`, then removing the `excluded_categories`. Priority is given to `excluded_categories` in the case of collisions.Filter patterns supported:- `*`: All categories- `PRIMARY.*`: All categories within the specified primary category- `PRIMARY.SECONDARY`: A specific income categoryFor a list of income categories, see the [Income V2 Category Taxonomy](https://plaid.com/documents/income-v2-category-taxonomy.csv).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Plaid.OpenApiClient.Models.IncomeInsightsFilter? IncomeInsightsFilter { get; set; }
#nullable restore
#else
        public global::Soenneker.Plaid.OpenApiClient.Models.IncomeInsightsFilter IncomeInsightsFilter { get; set; }
#endif
        /// <summary>The version of Income Insights to use.</summary>
        public global::Soenneker.Plaid.OpenApiClient.Models.IncomeInsightsVersion? IncomeInsightsVersion { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Plaid.OpenApiClient.Models.CraCheckReportIncomeInsightsGetOptions"/> and sets the default values.
        /// </summary>
        public CraCheckReportIncomeInsightsGetOptions()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Plaid.OpenApiClient.Models.CraCheckReportIncomeInsightsGetOptions"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Plaid.OpenApiClient.Models.CraCheckReportIncomeInsightsGetOptions CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Plaid.OpenApiClient.Models.CraCheckReportIncomeInsightsGetOptions();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "income_insights_filter", n => { IncomeInsightsFilter = n.GetObjectValue<global::Soenneker.Plaid.OpenApiClient.Models.IncomeInsightsFilter>(global::Soenneker.Plaid.OpenApiClient.Models.IncomeInsightsFilter.CreateFromDiscriminatorValue); } },
                { "income_insights_version", n => { IncomeInsightsVersion = n.GetEnumValue<global::Soenneker.Plaid.OpenApiClient.Models.IncomeInsightsVersion>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Plaid.OpenApiClient.Models.IncomeInsightsFilter>("income_insights_filter", IncomeInsightsFilter);
            writer.WriteEnumValue<global::Soenneker.Plaid.OpenApiClient.Models.IncomeInsightsVersion>("income_insights_version", IncomeInsightsVersion);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
