// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Plaid.OpenApiClient.Models
{
    /// <summary>
    /// Contains loan data to register.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CraLoanRegister : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Contains loan application data to register.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Plaid.OpenApiClient.Models.CraLoanRegisterApplication? Application { get; set; }
#nullable restore
#else
        public global::Soenneker.Plaid.OpenApiClient.Models.CraLoanRegisterApplication Application { get; set; }
#endif
        /// <summary>The total amount of the approved loan.</summary>
        public double? LoanAmount { get; set; }
        /// <summary>A unique identifier for the loan.Personally identifiable information, such as an email address or phone number, should not be used in the `loan_id`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LoanId { get; set; }
#nullable restore
#else
        public string LoanId { get; set; }
#endif
        /// <summary>The date the loan account was opened. The date should be in ISO 8601 format (YYYY-MM-DD).</summary>
        public Date? OpenedDate { get; set; }
        /// <summary>Contains the status and date information of the loan when registering.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Plaid.OpenApiClient.Models.CraLoanOpenedStatus? OpenedWithStatus { get; set; }
#nullable restore
#else
        public global::Soenneker.Plaid.OpenApiClient.Models.CraLoanOpenedStatus OpenedWithStatus { get; set; }
#endif
        /// <summary>The frequency of a loan&apos;s payment schedule.`BIWEEKLY` represents one payment every two weeks.</summary>
        public global::Soenneker.Plaid.OpenApiClient.Models.CraLoanPaymentSchedule? PaymentSchedule { get; set; }
        /// <summary>The type of loan the user applied for.</summary>
        public global::Soenneker.Plaid.OpenApiClient.Models.CraLoanType? Type { get; set; }
        /// <summary>The user token for the user associated with the loan.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UserToken { get; set; }
#nullable restore
#else
        public string UserToken { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Plaid.OpenApiClient.Models.CraLoanRegister"/> and sets the default values.
        /// </summary>
        public CraLoanRegister()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Plaid.OpenApiClient.Models.CraLoanRegister"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Plaid.OpenApiClient.Models.CraLoanRegister CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Plaid.OpenApiClient.Models.CraLoanRegister();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "application", n => { Application = n.GetObjectValue<global::Soenneker.Plaid.OpenApiClient.Models.CraLoanRegisterApplication>(global::Soenneker.Plaid.OpenApiClient.Models.CraLoanRegisterApplication.CreateFromDiscriminatorValue); } },
                { "loan_amount", n => { LoanAmount = n.GetDoubleValue(); } },
                { "loan_id", n => { LoanId = n.GetStringValue(); } },
                { "opened_date", n => { OpenedDate = n.GetDateValue(); } },
                { "opened_with_status", n => { OpenedWithStatus = n.GetObjectValue<global::Soenneker.Plaid.OpenApiClient.Models.CraLoanOpenedStatus>(global::Soenneker.Plaid.OpenApiClient.Models.CraLoanOpenedStatus.CreateFromDiscriminatorValue); } },
                { "payment_schedule", n => { PaymentSchedule = n.GetEnumValue<global::Soenneker.Plaid.OpenApiClient.Models.CraLoanPaymentSchedule>(); } },
                { "type", n => { Type = n.GetEnumValue<global::Soenneker.Plaid.OpenApiClient.Models.CraLoanType>(); } },
                { "user_token", n => { UserToken = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Plaid.OpenApiClient.Models.CraLoanRegisterApplication>("application", Application);
            writer.WriteDoubleValue("loan_amount", LoanAmount);
            writer.WriteStringValue("loan_id", LoanId);
            writer.WriteDateValue("opened_date", OpenedDate);
            writer.WriteObjectValue<global::Soenneker.Plaid.OpenApiClient.Models.CraLoanOpenedStatus>("opened_with_status", OpenedWithStatus);
            writer.WriteEnumValue<global::Soenneker.Plaid.OpenApiClient.Models.CraLoanPaymentSchedule>("payment_schedule", PaymentSchedule);
            writer.WriteEnumValue<global::Soenneker.Plaid.OpenApiClient.Models.CraLoanType>("type", Type);
            writer.WriteStringValue("user_token", UserToken);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
