// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Plaid.OpenApiClient.Models
{
    /// <summary>The version of the base FICO score model.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum CraPartnerInsightsBaseFicoScoreVersion
    {
        [EnumMember(Value = "8")]
        #pragma warning disable CS1591
        Eight,
        #pragma warning restore CS1591
        [EnumMember(Value = "9")]
        #pragma warning disable CS1591
        Nine,
        #pragma warning restore CS1591
        [EnumMember(Value = "10T")]
        #pragma warning disable CS1591
        OneZeroT,
        #pragma warning restore CS1591
    }
}
