// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Plaid.OpenApiClient.Models
{
    /// <summary>A list of add-ons that can be included in the PDF.`cra_income_insights`: Include Income Insights report in the PDF.`cra_partner_insights`: Include Partner Insights report in the PDF.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum CraPDFAddOns
    {
        [EnumMember(Value = "cra_income_insights")]
        #pragma warning disable CS1591
        Cra_income_insights,
        #pragma warning restore CS1591
        [EnumMember(Value = "cra_partner_insights")]
        #pragma warning disable CS1591
        Cra_partner_insights,
        #pragma warning restore CS1591
    }
}
