// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Plaid.OpenApiClient.Models
{
    /// <summary>
    /// Summary for bank income across all income sources and items (max history of 730 days).
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CreditBankIncomeSummary : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The latest date in which all income sources identified by Plaid appear in the user&apos;s account.The date will be returned in an ISO 8601 format (YYYY-MM-DD).</summary>
        public Date? EndDate { get; set; }
        /// <summary>The historical_summary property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Plaid.OpenApiClient.Models.CreditBankIncomeHistoricalSummary>? HistoricalSummary { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Plaid.OpenApiClient.Models.CreditBankIncomeHistoricalSummary> HistoricalSummary { get; set; }
#endif
        /// <summary>Number of income categories per end user.</summary>
        public int? IncomeCategoriesCount { get; set; }
        /// <summary>Number of income sources per end user.</summary>
        public int? IncomeSourcesCount { get; set; }
        /// <summary>Number of income transactions per end user.</summary>
        public int? IncomeTransactionsCount { get; set; }
        /// <summary>The ISO 4217 currency code of the amount or balance.Please use [`total_amounts`](https://plaid.com/docs/api/products/income/#credit-bank_income-get-response-bank-income-bank-income-summary-total-amounts) instead.</summary>
        [Obsolete("")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? IsoCurrencyCode { get; set; }
#nullable restore
#else
        public string IsoCurrencyCode { get; set; }
#endif
        /// <summary>The earliest date within the days requested in which all income sources identified by Plaid appear in a user&apos;s account.The date will be returned in an ISO 8601 format (YYYY-MM-DD).</summary>
        public Date? StartDate { get; set; }
        /// <summary>Total amount of earnings across all the income sources in the end user&apos;s Items for the days requested by the client.This may return an incorrect value if the summary includes income sources in multiple currencies.Please use [`total_amounts`](https://plaid.com/docs/api/products/income/#credit-bank_income-get-response-bank-income-bank-income-summary-total-amounts) instead.</summary>
        [Obsolete("")]
        public double? TotalAmount { get; set; }
        /// <summary>Total amount of earnings across all the income sources in the end user&apos;s Items for the days requested by the client.This can contain multiple amounts, with each amount denominated in one unique currency.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Plaid.OpenApiClient.Models.CreditAmountWithCurrency>? TotalAmounts { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Plaid.OpenApiClient.Models.CreditAmountWithCurrency> TotalAmounts { get; set; }
#endif
        /// <summary>The unofficial currency code associated with the amount or balance. Always `null` if `iso_currency_code` is non-null.Unofficial currency codes are used for currencies that do not have official ISO currency codes, such as cryptocurrencies and the currencies of certain countries.Please use [`total_amounts`](https://plaid.com/docs/api/products/income/#credit-bank_income-get-response-bank-income-bank-income-summary-total-amounts) instead.</summary>
        [Obsolete("")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UnofficialCurrencyCode { get; set; }
#nullable restore
#else
        public string UnofficialCurrencyCode { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Plaid.OpenApiClient.Models.CreditBankIncomeSummary"/> and sets the default values.
        /// </summary>
        public CreditBankIncomeSummary()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Plaid.OpenApiClient.Models.CreditBankIncomeSummary"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Plaid.OpenApiClient.Models.CreditBankIncomeSummary CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Plaid.OpenApiClient.Models.CreditBankIncomeSummary();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "end_date", n => { EndDate = n.GetDateValue(); } },
                { "historical_summary", n => { HistoricalSummary = n.GetCollectionOfObjectValues<global::Soenneker.Plaid.OpenApiClient.Models.CreditBankIncomeHistoricalSummary>(global::Soenneker.Plaid.OpenApiClient.Models.CreditBankIncomeHistoricalSummary.CreateFromDiscriminatorValue)?.AsList(); } },
                { "income_categories_count", n => { IncomeCategoriesCount = n.GetIntValue(); } },
                { "income_sources_count", n => { IncomeSourcesCount = n.GetIntValue(); } },
                { "income_transactions_count", n => { IncomeTransactionsCount = n.GetIntValue(); } },
                { "iso_currency_code", n => { IsoCurrencyCode = n.GetStringValue(); } },
                { "start_date", n => { StartDate = n.GetDateValue(); } },
                { "total_amount", n => { TotalAmount = n.GetDoubleValue(); } },
                { "total_amounts", n => { TotalAmounts = n.GetCollectionOfObjectValues<global::Soenneker.Plaid.OpenApiClient.Models.CreditAmountWithCurrency>(global::Soenneker.Plaid.OpenApiClient.Models.CreditAmountWithCurrency.CreateFromDiscriminatorValue)?.AsList(); } },
                { "unofficial_currency_code", n => { UnofficialCurrencyCode = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDateValue("end_date", EndDate);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Plaid.OpenApiClient.Models.CreditBankIncomeHistoricalSummary>("historical_summary", HistoricalSummary);
            writer.WriteIntValue("income_categories_count", IncomeCategoriesCount);
            writer.WriteIntValue("income_sources_count", IncomeSourcesCount);
            writer.WriteIntValue("income_transactions_count", IncomeTransactionsCount);
            writer.WriteStringValue("iso_currency_code", IsoCurrencyCode);
            writer.WriteDateValue("start_date", StartDate);
            writer.WriteDoubleValue("total_amount", TotalAmount);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Plaid.OpenApiClient.Models.CreditAmountWithCurrency>("total_amounts", TotalAmounts);
            writer.WriteStringValue("unofficial_currency_code", UnofficialCurrencyCode);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
