// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Plaid.OpenApiClient.Models
{
    /// <summary>Specifies the use case of the transfer. Required for transfers on an ACH network.`&quot;ccd&quot;` - Corporate Credit or Debit - fund transfer between two corporate bank accounts`&quot;ppd&quot;` - Prearranged Payment or Deposit - The transfer is part of a pre-existing relationship with a consumer. Authorization was obtained in writing either in person or via an electronic document signing, e.g. Docusign, by the consumer. Can be used for credits or debits.`&quot;web&quot;` - Internet-Initiated Entry. The transfer debits a consumer’s bank account. Authorization from the consumer is obtained over the Internet (e.g. a web or mobile application). Can be used for single debits or recurring debits.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum CreditACHClass
    {
        [EnumMember(Value = "ccd")]
        #pragma warning disable CS1591
        Ccd,
        #pragma warning restore CS1591
        [EnumMember(Value = "ppd")]
        #pragma warning disable CS1591
        Ppd,
        #pragma warning restore CS1591
        [EnumMember(Value = "web")]
        #pragma warning disable CS1591
        Web,
        #pragma warning restore CS1591
    }
}
