// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Plaid.OpenApiClient.Models
{
    /// <summary>
    /// Details of consent or payment network identifier or other entity&apos;s revocation request or other lifecycle status change event
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class FDXLifecycleEvent : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Identifies the type of a party</summary>
        public global::Soenneker.Plaid.OpenApiClient.Models.FDXPartyType? Initiator { get; set; }
        /// <summary>Additional information or description of an `OTHER` reason</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OtherReason { get; set; }
#nullable restore
#else
        public string OtherReason { get; set; }
#endif
        /// <summary>Reason for lifecycle event status change</summary>
        public global::Soenneker.Plaid.OpenApiClient.Models.FDXUpdateReason? Reason { get; set; }
        /// <summary>Current status of indicated entity after reported event change. Not all statuses will be supported on all entity types by all data providers</summary>
        public global::Soenneker.Plaid.OpenApiClient.Models.FDXEventStatus? Status { get; set; }
        /// <summary>ISO 8601 date-time in format &apos;YYYY-MM-DDThh:mm:ss.nnn[Z|[+|-]hh:mm]&apos; according to [IETF RFC3339](https://xml2rfc.tools.ietf.org/public/rfc/html/rfc3339.html#anchor14)</summary>
        public DateTimeOffset? UpdatedTime { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Plaid.OpenApiClient.Models.FDXLifecycleEvent"/> and sets the default values.
        /// </summary>
        public FDXLifecycleEvent()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Plaid.OpenApiClient.Models.FDXLifecycleEvent"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Plaid.OpenApiClient.Models.FDXLifecycleEvent CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Plaid.OpenApiClient.Models.FDXLifecycleEvent();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "initiator", n => { Initiator = n.GetEnumValue<global::Soenneker.Plaid.OpenApiClient.Models.FDXPartyType>(); } },
                { "otherReason", n => { OtherReason = n.GetStringValue(); } },
                { "reason", n => { Reason = n.GetEnumValue<global::Soenneker.Plaid.OpenApiClient.Models.FDXUpdateReason>(); } },
                { "status", n => { Status = n.GetEnumValue<global::Soenneker.Plaid.OpenApiClient.Models.FDXEventStatus>(); } },
                { "updatedTime", n => { UpdatedTime = n.GetDateTimeOffsetValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteEnumValue<global::Soenneker.Plaid.OpenApiClient.Models.FDXPartyType>("initiator", Initiator);
            writer.WriteStringValue("otherReason", OtherReason);
            writer.WriteEnumValue<global::Soenneker.Plaid.OpenApiClient.Models.FDXUpdateReason>("reason", Reason);
            writer.WriteEnumValue<global::Soenneker.Plaid.OpenApiClient.Models.FDXEventStatus>("status", Status);
            writer.WriteDateTimeOffsetValue("updatedTime", UpdatedTime);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
