// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Plaid.OpenApiClient.Models
{
    /// <summary>
    /// FDX Participant - an entity or person that is a part of a FDX API transaction
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class FDXParty : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>URI for party, where an end user could learn more about the company or application involved in the data sharing chain</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? HomeUri { get; set; }
#nullable restore
#else
        public string HomeUri { get; set; }
#endif
        /// <summary>URI for a logo asset to be displayed to the end user</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LogoUri { get; set; }
#nullable restore
#else
        public string LogoUri { get; set; }
#endif
        /// <summary>Human recognizable common name</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>Registered id of party</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RegisteredEntityId { get; set; }
#nullable restore
#else
        public string RegisteredEntityId { get; set; }
#endif
        /// <summary>Registered name of party</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RegisteredEntityName { get; set; }
#nullable restore
#else
        public string RegisteredEntityName { get; set; }
#endif
        /// <summary>The registry containing the party’s registration with name and id</summary>
        public global::Soenneker.Plaid.OpenApiClient.Models.FDXPartyRegistry? Registry { get; set; }
        /// <summary>Identifies the type of a party</summary>
        public global::Soenneker.Plaid.OpenApiClient.Models.FDXPartyType? Type { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Plaid.OpenApiClient.Models.FDXParty"/> and sets the default values.
        /// </summary>
        public FDXParty()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Plaid.OpenApiClient.Models.FDXParty"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Plaid.OpenApiClient.Models.FDXParty CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Plaid.OpenApiClient.Models.FDXParty();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "homeUri", n => { HomeUri = n.GetStringValue(); } },
                { "logoUri", n => { LogoUri = n.GetStringValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "registeredEntityId", n => { RegisteredEntityId = n.GetStringValue(); } },
                { "registeredEntityName", n => { RegisteredEntityName = n.GetStringValue(); } },
                { "registry", n => { Registry = n.GetEnumValue<global::Soenneker.Plaid.OpenApiClient.Models.FDXPartyRegistry>(); } },
                { "type", n => { Type = n.GetEnumValue<global::Soenneker.Plaid.OpenApiClient.Models.FDXPartyType>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("homeUri", HomeUri);
            writer.WriteStringValue("logoUri", LogoUri);
            writer.WriteStringValue("name", Name);
            writer.WriteStringValue("registeredEntityId", RegisteredEntityId);
            writer.WriteStringValue("registeredEntityName", RegisteredEntityName);
            writer.WriteEnumValue<global::Soenneker.Plaid.OpenApiClient.Models.FDXPartyRegistry>("registry", Registry);
            writer.WriteEnumValue<global::Soenneker.Plaid.OpenApiClient.Models.FDXPartyType>("type", Type);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
