// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Plaid.OpenApiClient.Models
{
    /// <summary>The status of the incident.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum IncidentUpdate_status
    {
        [EnumMember(Value = "INVESTIGATING")]
        #pragma warning disable CS1591
        INVESTIGATING,
        #pragma warning restore CS1591
        [EnumMember(Value = "IDENTIFIED")]
        #pragma warning disable CS1591
        IDENTIFIED,
        #pragma warning restore CS1591
        [EnumMember(Value = "SCHEDULED")]
        #pragma warning disable CS1591
        SCHEDULED,
        #pragma warning restore CS1591
        [EnumMember(Value = "RESOLVED")]
        #pragma warning disable CS1591
        RESOLVED,
        #pragma warning restore CS1591
        [EnumMember(Value = "UNKNOWN")]
        #pragma warning disable CS1591
        UNKNOWN,
        #pragma warning restore CS1591
    }
}
