// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Plaid.OpenApiClient.Models
{
    /// <summary>The confidence that Plaid can support the user in the digital income verification flow instead of requiring a manual paystub upload. One of the following:`&quot;HIGH&quot;`: It is very likely that this user can use the digital income verification flow.&quot;`LOW`&quot;: It is unlikely that this user can use the digital income verification flow.`&quot;UNKNOWN&quot;`: It was not possible to determine if the user is supportable with the information passed.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum IncomeVerificationPrecheckConfidence
    {
        [EnumMember(Value = "HIGH")]
        #pragma warning disable CS1591
        HIGH,
        #pragma warning restore CS1591
        [EnumMember(Value = "LOW")]
        #pragma warning disable CS1591
        LOW,
        #pragma warning restore CS1591
        [EnumMember(Value = "UNKNOWN")]
        #pragma warning disable CS1591
        UNKNOWN,
        #pragma warning restore CS1591
    }
}
