// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Plaid.OpenApiClient.Models
{
    /// <summary>Value is one of the following:`buy`: Buying an investment`sell`: Selling an investment`cancel`: A cancellation of a pending transaction`cash`: Activity that modifies a cash position`fee`: A fee on the account`transfer`: Activity which modifies a position, but not through buy/sell activity e.g. options exercise, portfolio transferFor descriptions of possible transaction types and subtypes, see the [Investment transaction types schema](https://plaid.com/docs/api/accounts/#investment-transaction-types-schema).</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum InvestmentTransactionType
    {
        [EnumMember(Value = "buy")]
        #pragma warning disable CS1591
        Buy,
        #pragma warning restore CS1591
        [EnumMember(Value = "sell")]
        #pragma warning disable CS1591
        Sell,
        #pragma warning restore CS1591
        [EnumMember(Value = "cancel")]
        #pragma warning disable CS1591
        Cancel,
        #pragma warning restore CS1591
        [EnumMember(Value = "cash")]
        #pragma warning disable CS1591
        Cash,
        #pragma warning restore CS1591
        [EnumMember(Value = "fee")]
        #pragma warning disable CS1591
        Fee,
        #pragma warning restore CS1591
        [EnumMember(Value = "transfer")]
        #pragma warning disable CS1591
        Transfer,
        #pragma warning restore CS1591
    }
}
