// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Plaid.OpenApiClient.Models
{
    /// <summary>
    /// Identifying information for transferring holdings to an investments account.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class InvestmentsAuthGetNumbers : IAdditionalDataHolder, IParsable
    {
        /// <summary>The acats property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Plaid.OpenApiClient.Models.NumbersACATS>? Acats { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Plaid.OpenApiClient.Models.NumbersACATS> Acats { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The aton property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Plaid.OpenApiClient.Models.NumbersATON>? Aton { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Plaid.OpenApiClient.Models.NumbersATON> Aton { get; set; }
#endif
        /// <summary>The retirement_401k property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Plaid.OpenApiClient.Models.NumbersRetirement401k>? Retirement401k { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Plaid.OpenApiClient.Models.NumbersRetirement401k> Retirement401k { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Plaid.OpenApiClient.Models.InvestmentsAuthGetNumbers"/> and sets the default values.
        /// </summary>
        public InvestmentsAuthGetNumbers()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Plaid.OpenApiClient.Models.InvestmentsAuthGetNumbers"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Plaid.OpenApiClient.Models.InvestmentsAuthGetNumbers CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Plaid.OpenApiClient.Models.InvestmentsAuthGetNumbers();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "acats", n => { Acats = n.GetCollectionOfObjectValues<global::Soenneker.Plaid.OpenApiClient.Models.NumbersACATS>(global::Soenneker.Plaid.OpenApiClient.Models.NumbersACATS.CreateFromDiscriminatorValue)?.AsList(); } },
                { "aton", n => { Aton = n.GetCollectionOfObjectValues<global::Soenneker.Plaid.OpenApiClient.Models.NumbersATON>(global::Soenneker.Plaid.OpenApiClient.Models.NumbersATON.CreateFromDiscriminatorValue)?.AsList(); } },
                { "retirement_401k", n => { Retirement401k = n.GetCollectionOfObjectValues<global::Soenneker.Plaid.OpenApiClient.Models.NumbersRetirement401k>(global::Soenneker.Plaid.OpenApiClient.Models.NumbersRetirement401k.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::Soenneker.Plaid.OpenApiClient.Models.NumbersACATS>("acats", Acats);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Plaid.OpenApiClient.Models.NumbersATON>("aton", Aton);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Plaid.OpenApiClient.Models.NumbersRetirement401k>("retirement_401k", Retirement401k);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
