// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Plaid.OpenApiClient.Models
{
    /// <summary>Enum representing the entity authenticating the user.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ItemCreateAuthentication
    {
        [EnumMember(Value = "UNKNOWN")]
        #pragma warning disable CS1591
        UNKNOWN,
        #pragma warning restore CS1591
        [EnumMember(Value = "DATA_PARTNER")]
        #pragma warning disable CS1591
        DATA_PARTNER,
        #pragma warning restore CS1591
        [EnumMember(Value = "PLAID")]
        #pragma warning disable CS1591
        PLAID,
        #pragma warning restore CS1591
    }
}
