// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Plaid.OpenApiClient.Models
{
    /// <summary>A data scope for the products that a user can consent to in [Data Transparency Messaging](https://plaid.com/docs/link/data-transparency-messaging-migration-guide)</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ItemConsentedDataScope
    {
        [EnumMember(Value = "account_balance_info")]
        #pragma warning disable CS1591
        Account_balance_info,
        #pragma warning restore CS1591
        [EnumMember(Value = "contact_info")]
        #pragma warning disable CS1591
        Contact_info,
        #pragma warning restore CS1591
        [EnumMember(Value = "account_routing_number")]
        #pragma warning disable CS1591
        Account_routing_number,
        #pragma warning restore CS1591
        [EnumMember(Value = "transactions")]
        #pragma warning disable CS1591
        Transactions,
        #pragma warning restore CS1591
        [EnumMember(Value = "credit_loan_info")]
        #pragma warning disable CS1591
        Credit_loan_info,
        #pragma warning restore CS1591
        [EnumMember(Value = "investments")]
        #pragma warning disable CS1591
        Investments,
        #pragma warning restore CS1591
        [EnumMember(Value = "payroll_info")]
        #pragma warning disable CS1591
        Payroll_info,
        #pragma warning restore CS1591
        [EnumMember(Value = "income_verification_paystubs_info")]
        #pragma warning disable CS1591
        Income_verification_paystubs_info,
        #pragma warning restore CS1591
        [EnumMember(Value = "income_verification_w2s_info")]
        #pragma warning disable CS1591
        Income_verification_w2s_info,
        #pragma warning restore CS1591
        [EnumMember(Value = "income_verification_bank_statements")]
        #pragma warning disable CS1591
        Income_verification_bank_statements,
        #pragma warning restore CS1591
        [EnumMember(Value = "income_verification_employment_info")]
        #pragma warning disable CS1591
        Income_verification_employment_info,
        #pragma warning restore CS1591
        [EnumMember(Value = "bank_statements")]
        #pragma warning disable CS1591
        Bank_statements,
        #pragma warning restore CS1591
        [EnumMember(Value = "risk_info")]
        #pragma warning disable CS1591
        Risk_info,
        #pragma warning restore CS1591
        [EnumMember(Value = "network_insights_lite")]
        #pragma warning disable CS1591
        Network_insights_lite,
        #pragma warning restore CS1591
        [EnumMember(Value = "fraud_info")]
        #pragma warning disable CS1591
        Fraud_info,
        #pragma warning restore CS1591
    }
}
