// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Plaid.OpenApiClient.Models
{
    /// <summary>
    /// Specifies options for initializing Link for use with the Employment product. This field is required if `employment` is included in the `products` array.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class LinkTokenCreateRequestEmployment : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Specifies options for initializing Link for use with Bank Employment. This field is required if `employment` is included in the `products` array and `bank` is specified in `employment_source_types`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Plaid.OpenApiClient.Models.LinkTokenCreateRequestEmploymentBankIncome? BankEmployment { get; set; }
#nullable restore
#else
        public global::Soenneker.Plaid.OpenApiClient.Models.LinkTokenCreateRequestEmploymentBankIncome BankEmployment { get; set; }
#endif
        /// <summary>The types of source employment data that users will be permitted to share. Options include `bank` and `payroll`. Currently you can only specify one of these options.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Plaid.OpenApiClient.Models.EmploymentSourceType?>? EmploymentSourceTypes { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Plaid.OpenApiClient.Models.EmploymentSourceType?> EmploymentSourceTypes { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Plaid.OpenApiClient.Models.LinkTokenCreateRequestEmployment"/> and sets the default values.
        /// </summary>
        public LinkTokenCreateRequestEmployment()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Plaid.OpenApiClient.Models.LinkTokenCreateRequestEmployment"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Plaid.OpenApiClient.Models.LinkTokenCreateRequestEmployment CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Plaid.OpenApiClient.Models.LinkTokenCreateRequestEmployment();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "bank_employment", n => { BankEmployment = n.GetObjectValue<global::Soenneker.Plaid.OpenApiClient.Models.LinkTokenCreateRequestEmploymentBankIncome>(global::Soenneker.Plaid.OpenApiClient.Models.LinkTokenCreateRequestEmploymentBankIncome.CreateFromDiscriminatorValue); } },
                { "employment_source_types", n => { EmploymentSourceTypes = n.GetCollectionOfEnumValues<global::Soenneker.Plaid.OpenApiClient.Models.EmploymentSourceType>()?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Plaid.OpenApiClient.Models.LinkTokenCreateRequestEmploymentBankIncome>("bank_employment", BankEmployment);
            writer.WriteCollectionOfEnumValues<global::Soenneker.Plaid.OpenApiClient.Models.EmploymentSourceType>("employment_source_types", EmploymentSourceTypes);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
