// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Plaid.OpenApiClient.Models
{
    /// <summary>
    /// The point at which the user exited the Link flow. One of the following values.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class LinkSessionExitMetadata_status : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>User prompted to select a device on which to receive a one-time passcode</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? ChooseDevice { get; set; }
#nullable restore
#else
        public UntypedNode ChooseDevice { get; set; }
#endif
        /// <summary>User exited the Link flow after unsuccessfully (no results returned) searching for a financial institution</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? InstitutionNotFound { get; set; }
#nullable restore
#else
        public UntypedNode InstitutionNotFound { get; set; }
#endif
        /// <summary>User exited the Link flow after discovering their selected institution is no longer supported by Plaid</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? InstitutionNotSupported { get; set; }
#nullable restore
#else
        public UntypedNode InstitutionNotSupported { get; set; }
#endif
        /// <summary>User prompted to select one or more financial accounts to share</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? RequiresAccountSelection { get; set; }
#nullable restore
#else
        public UntypedNode RequiresAccountSelection { get; set; }
#endif
        /// <summary>User prompted to provide a one-time passcode</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? RequiresCode { get; set; }
#nullable restore
#else
        public UntypedNode RequiresCode { get; set; }
#endif
        /// <summary>User prompted to provide credentials for the selected financial institution or has not yet selected a financial institution</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? RequiresCredentials { get; set; }
#nullable restore
#else
        public UntypedNode RequiresCredentials { get; set; }
#endif
        /// <summary>User prompted to enter an OAuth flow</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? RequiresOauth { get; set; }
#nullable restore
#else
        public UntypedNode RequiresOauth { get; set; }
#endif
        /// <summary>User prompted to answer security questions</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? RequiresQuestions { get; set; }
#nullable restore
#else
        public UntypedNode RequiresQuestions { get; set; }
#endif
        /// <summary>User prompted to answer multiple choice question(s)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? RequiresSelections { get; set; }
#nullable restore
#else
        public UntypedNode RequiresSelections { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Plaid.OpenApiClient.Models.LinkSessionExitMetadata_status"/> and sets the default values.
        /// </summary>
        public LinkSessionExitMetadata_status()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Plaid.OpenApiClient.Models.LinkSessionExitMetadata_status"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Plaid.OpenApiClient.Models.LinkSessionExitMetadata_status CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Plaid.OpenApiClient.Models.LinkSessionExitMetadata_status();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "choose_device", n => { ChooseDevice = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "institution_not_found", n => { InstitutionNotFound = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "institution_not_supported", n => { InstitutionNotSupported = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "requires_account_selection", n => { RequiresAccountSelection = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "requires_code", n => { RequiresCode = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "requires_credentials", n => { RequiresCredentials = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "requires_oauth", n => { RequiresOauth = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "requires_questions", n => { RequiresQuestions = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "requires_selections", n => { RequiresSelections = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<UntypedNode>("choose_device", ChooseDevice);
            writer.WriteObjectValue<UntypedNode>("institution_not_found", InstitutionNotFound);
            writer.WriteObjectValue<UntypedNode>("institution_not_supported", InstitutionNotSupported);
            writer.WriteObjectValue<UntypedNode>("requires_account_selection", RequiresAccountSelection);
            writer.WriteObjectValue<UntypedNode>("requires_code", RequiresCode);
            writer.WriteObjectValue<UntypedNode>("requires_credentials", RequiresCredentials);
            writer.WriteObjectValue<UntypedNode>("requires_oauth", RequiresOauth);
            writer.WriteObjectValue<UntypedNode>("requires_questions", RequiresQuestions);
            writer.WriteObjectValue<UntypedNode>("requires_selections", RequiresSelections);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
