// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Plaid.OpenApiClient.Models
{
    /// <summary>
    /// Specifies options for initializing Link for use with the Income product. This field is required if `income_verification` is included in the `products` array.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class LinkTokenCreateRequestIncomeVerification : IAdditionalDataHolder, IParsable
    {
        /// <summary>An array of access tokens corresponding to Items that a user has previously connected with. Data from these institutions will be cross-referenced with document data received during the Document Income flow to help verify that the uploaded documents are accurate. If the `transactions` product was not initialized for these Items during link, it will be initialized after this Link session.This field should only be used with the `payroll` income source type.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? AccessTokens { get; set; }
#nullable restore
#else
        public List<string> AccessTokens { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The `asset_report_id` of an asset report associated with the user, as provided by `/asset_report/create`. Providing an `asset_report_id` is optional and can be used to verify the user through a streamlined flow. If provided, the bank linking flow will be skipped.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AssetReportId { get; set; }
#nullable restore
#else
        public string AssetReportId { get; set; }
#endif
        /// <summary>Specifies options for initializing Link for use with Bank Income. This field is required if `income_verification` is included in the `products` array and `bank` is specified in `income_source_types`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Plaid.OpenApiClient.Models.LinkTokenCreateRequestIncomeVerificationBankIncome? BankIncome { get; set; }
#nullable restore
#else
        public global::Soenneker.Plaid.OpenApiClient.Models.LinkTokenCreateRequestIncomeVerificationBankIncome BankIncome { get; set; }
#endif
        /// <summary>The types of source income data that users will be permitted to share. Options include `bank` and `payroll`. Currently you can only specify one of these options.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Plaid.OpenApiClient.Models.IncomeVerificationSourceType?>? IncomeSourceTypes { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Plaid.OpenApiClient.Models.IncomeVerificationSourceType?> IncomeSourceTypes { get; set; }
#endif
        /// <summary>The `income_verification_id` of the verification instance, as provided by `/income/verification/create`. Replaced by the user token.</summary>
        [Obsolete("")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? IncomeVerificationId { get; set; }
#nullable restore
#else
        public string IncomeVerificationId { get; set; }
#endif
        /// <summary>Specifies options for initializing Link for use with Payroll Income (including Document Income). Further customization options for Document Income, such as customizing which document types may be uploaded, are also available via the [Link Customization pane](https://dashboard.plaid.com/link) in the Dashboard. (Requires Production enablement.)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Plaid.OpenApiClient.Models.LinkTokenCreateRequestIncomeVerificationPayrollIncome? PayrollIncome { get; set; }
#nullable restore
#else
        public global::Soenneker.Plaid.OpenApiClient.Models.LinkTokenCreateRequestIncomeVerificationPayrollIncome PayrollIncome { get; set; }
#endif
        /// <summary>A list of user stated income sources</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Plaid.OpenApiClient.Models.LinkTokenCreateRequestUserStatedIncomeSource>? StatedIncomeSources { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Plaid.OpenApiClient.Models.LinkTokenCreateRequestUserStatedIncomeSource> StatedIncomeSources { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Plaid.OpenApiClient.Models.LinkTokenCreateRequestIncomeVerification"/> and sets the default values.
        /// </summary>
        public LinkTokenCreateRequestIncomeVerification()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Plaid.OpenApiClient.Models.LinkTokenCreateRequestIncomeVerification"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Plaid.OpenApiClient.Models.LinkTokenCreateRequestIncomeVerification CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Plaid.OpenApiClient.Models.LinkTokenCreateRequestIncomeVerification();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "access_tokens", n => { AccessTokens = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "asset_report_id", n => { AssetReportId = n.GetStringValue(); } },
                { "bank_income", n => { BankIncome = n.GetObjectValue<global::Soenneker.Plaid.OpenApiClient.Models.LinkTokenCreateRequestIncomeVerificationBankIncome>(global::Soenneker.Plaid.OpenApiClient.Models.LinkTokenCreateRequestIncomeVerificationBankIncome.CreateFromDiscriminatorValue); } },
                { "income_source_types", n => { IncomeSourceTypes = n.GetCollectionOfEnumValues<global::Soenneker.Plaid.OpenApiClient.Models.IncomeVerificationSourceType>()?.AsList(); } },
                { "income_verification_id", n => { IncomeVerificationId = n.GetStringValue(); } },
                { "payroll_income", n => { PayrollIncome = n.GetObjectValue<global::Soenneker.Plaid.OpenApiClient.Models.LinkTokenCreateRequestIncomeVerificationPayrollIncome>(global::Soenneker.Plaid.OpenApiClient.Models.LinkTokenCreateRequestIncomeVerificationPayrollIncome.CreateFromDiscriminatorValue); } },
                { "stated_income_sources", n => { StatedIncomeSources = n.GetCollectionOfObjectValues<global::Soenneker.Plaid.OpenApiClient.Models.LinkTokenCreateRequestUserStatedIncomeSource>(global::Soenneker.Plaid.OpenApiClient.Models.LinkTokenCreateRequestUserStatedIncomeSource.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfPrimitiveValues<string>("access_tokens", AccessTokens);
            writer.WriteStringValue("asset_report_id", AssetReportId);
            writer.WriteObjectValue<global::Soenneker.Plaid.OpenApiClient.Models.LinkTokenCreateRequestIncomeVerificationBankIncome>("bank_income", BankIncome);
            writer.WriteCollectionOfEnumValues<global::Soenneker.Plaid.OpenApiClient.Models.IncomeVerificationSourceType>("income_source_types", IncomeSourceTypes);
            writer.WriteStringValue("income_verification_id", IncomeVerificationId);
            writer.WriteObjectValue<global::Soenneker.Plaid.OpenApiClient.Models.LinkTokenCreateRequestIncomeVerificationPayrollIncome>("payroll_income", PayrollIncome);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Plaid.OpenApiClient.Models.LinkTokenCreateRequestUserStatedIncomeSource>("stated_income_sources", StatedIncomeSources);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
