// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Plaid.OpenApiClient.Models
{
    /// <summary>
    /// Specifies options for initializing Link for use with Plaid Check products
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class LinkTokenCreateRequestCraOptions : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Specifies options for initializing Link for use with the Base Report product, specifically the `client_report_id`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Plaid.OpenApiClient.Models.LinkTokenCreateRequestCraOptionsBaseReport? BaseReport { get; set; }
#nullable restore
#else
        public global::Soenneker.Plaid.OpenApiClient.Models.LinkTokenCreateRequestCraOptionsBaseReport BaseReport { get; set; }
#endif
        /// <summary>Specifies options for initializing Link for use with the Cashflow Insights product.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Plaid.OpenApiClient.Models.LinkTokenCreateRequestCraOptionsCashflowInsights? CashflowInsights { get; set; }
#nullable restore
#else
        public global::Soenneker.Plaid.OpenApiClient.Models.LinkTokenCreateRequestCraOptionsCashflowInsights CashflowInsights { get; set; }
#endif
        /// <summary>Client-generated identifier, which can be used by lenders to track loan applications.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ClientReportId { get; set; }
#nullable restore
#else
        public string ClientReportId { get; set; }
#endif
        /// <summary>The number of days of history to include in Plaid Check products. Maximum is 731; minimum is 180. If a value lower than 180 is provided, a minimum of 180 days of history will be requested.</summary>
        public int? DaysRequested { get; set; }
        /// <summary>The minimum number of days of data required for the report to be successfully generated.</summary>
        public int? DaysRequired { get; set; }
        /// <summary>Indicates that investment data should be extracted from the linked account(s).</summary>
        public bool? IncludeInvestments { get; set; }
        /// <summary>Specifies options for initializing Link for use with the CRA Income Insights product.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Plaid.OpenApiClient.Models.LinkTokenCreateRequestCraOptionsIncomeInsights? IncomeInsights { get; set; }
#nullable restore
#else
        public global::Soenneker.Plaid.OpenApiClient.Models.LinkTokenCreateRequestCraOptionsIncomeInsights IncomeInsights { get; set; }
#endif
        /// <summary>Specifies options for initializing Link for use with the CRA LendScore product.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Plaid.OpenApiClient.Models.LinkTokenCreateRequestCraOptionsLendScore? LendScore { get; set; }
#nullable restore
#else
        public global::Soenneker.Plaid.OpenApiClient.Models.LinkTokenCreateRequestCraOptionsLendScore LendScore { get; set; }
#endif
        /// <summary>Specifies options for initializing Link for use with the CRA Network Insights product.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Plaid.OpenApiClient.Models.LinkTokenCreateRequestCraOptionsNetworkInsights? NetworkInsights { get; set; }
#nullable restore
#else
        public global::Soenneker.Plaid.OpenApiClient.Models.LinkTokenCreateRequestCraOptionsNetworkInsights NetworkInsights { get; set; }
#endif
        /// <summary>Specifies options for initializing Link for use with the Credit Partner Insights product.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Plaid.OpenApiClient.Models.LinkTokenCreateRequestCraOptionsPartnerInsights? PartnerInsights { get; set; }
#nullable restore
#else
        public global::Soenneker.Plaid.OpenApiClient.Models.LinkTokenCreateRequestCraOptionsPartnerInsights PartnerInsights { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Plaid.OpenApiClient.Models.LinkTokenCreateRequestCraOptions"/> and sets the default values.
        /// </summary>
        public LinkTokenCreateRequestCraOptions()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Plaid.OpenApiClient.Models.LinkTokenCreateRequestCraOptions"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Plaid.OpenApiClient.Models.LinkTokenCreateRequestCraOptions CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Plaid.OpenApiClient.Models.LinkTokenCreateRequestCraOptions();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "base_report", n => { BaseReport = n.GetObjectValue<global::Soenneker.Plaid.OpenApiClient.Models.LinkTokenCreateRequestCraOptionsBaseReport>(global::Soenneker.Plaid.OpenApiClient.Models.LinkTokenCreateRequestCraOptionsBaseReport.CreateFromDiscriminatorValue); } },
                { "cashflow_insights", n => { CashflowInsights = n.GetObjectValue<global::Soenneker.Plaid.OpenApiClient.Models.LinkTokenCreateRequestCraOptionsCashflowInsights>(global::Soenneker.Plaid.OpenApiClient.Models.LinkTokenCreateRequestCraOptionsCashflowInsights.CreateFromDiscriminatorValue); } },
                { "client_report_id", n => { ClientReportId = n.GetStringValue(); } },
                { "days_requested", n => { DaysRequested = n.GetIntValue(); } },
                { "days_required", n => { DaysRequired = n.GetIntValue(); } },
                { "include_investments", n => { IncludeInvestments = n.GetBoolValue(); } },
                { "income_insights", n => { IncomeInsights = n.GetObjectValue<global::Soenneker.Plaid.OpenApiClient.Models.LinkTokenCreateRequestCraOptionsIncomeInsights>(global::Soenneker.Plaid.OpenApiClient.Models.LinkTokenCreateRequestCraOptionsIncomeInsights.CreateFromDiscriminatorValue); } },
                { "lend_score", n => { LendScore = n.GetObjectValue<global::Soenneker.Plaid.OpenApiClient.Models.LinkTokenCreateRequestCraOptionsLendScore>(global::Soenneker.Plaid.OpenApiClient.Models.LinkTokenCreateRequestCraOptionsLendScore.CreateFromDiscriminatorValue); } },
                { "network_insights", n => { NetworkInsights = n.GetObjectValue<global::Soenneker.Plaid.OpenApiClient.Models.LinkTokenCreateRequestCraOptionsNetworkInsights>(global::Soenneker.Plaid.OpenApiClient.Models.LinkTokenCreateRequestCraOptionsNetworkInsights.CreateFromDiscriminatorValue); } },
                { "partner_insights", n => { PartnerInsights = n.GetObjectValue<global::Soenneker.Plaid.OpenApiClient.Models.LinkTokenCreateRequestCraOptionsPartnerInsights>(global::Soenneker.Plaid.OpenApiClient.Models.LinkTokenCreateRequestCraOptionsPartnerInsights.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Plaid.OpenApiClient.Models.LinkTokenCreateRequestCraOptionsBaseReport>("base_report", BaseReport);
            writer.WriteObjectValue<global::Soenneker.Plaid.OpenApiClient.Models.LinkTokenCreateRequestCraOptionsCashflowInsights>("cashflow_insights", CashflowInsights);
            writer.WriteStringValue("client_report_id", ClientReportId);
            writer.WriteIntValue("days_requested", DaysRequested);
            writer.WriteIntValue("days_required", DaysRequired);
            writer.WriteBoolValue("include_investments", IncludeInvestments);
            writer.WriteObjectValue<global::Soenneker.Plaid.OpenApiClient.Models.LinkTokenCreateRequestCraOptionsIncomeInsights>("income_insights", IncomeInsights);
            writer.WriteObjectValue<global::Soenneker.Plaid.OpenApiClient.Models.LinkTokenCreateRequestCraOptionsLendScore>("lend_score", LendScore);
            writer.WriteObjectValue<global::Soenneker.Plaid.OpenApiClient.Models.LinkTokenCreateRequestCraOptionsNetworkInsights>("network_insights", NetworkInsights);
            writer.WriteObjectValue<global::Soenneker.Plaid.OpenApiClient.Models.LinkTokenCreateRequestCraOptionsPartnerInsights>("partner_insights", PartnerInsights);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
