// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Plaid.OpenApiClient.Models
{
    /// <summary>
    /// Insights into negative balance occurrences, including frequency, duration, and minimum balance details.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class NegativeBalanceInsights : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The number of days since the last transaction that caused any account in the report to have a negative balance.This value is inclusive of the date of the last negative balance, meaning that if the last negative balance occurred today, this value will be `0`.</summary>
        public int? DaysSinceLastOccurrence { get; set; }
        /// <summary>The number of aggregated days that the accounts in the report has had a negative balance within the given time window.</summary>
        public int? DaysWithNegativeBalance { get; set; }
        /// <summary>A monetary amount with its associated currency information, supporting both official and unofficial currency codes.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Plaid.OpenApiClient.Models.AmountWithCurrency? MinimumBalance { get; set; }
#nullable restore
#else
        public global::Soenneker.Plaid.OpenApiClient.Models.AmountWithCurrency MinimumBalance { get; set; }
#endif
        /// <summary>The summary of the negative balance occurrences for this account.If the user has not had a negative balance in the account in the given time window, this list will be empty.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Plaid.OpenApiClient.Models.NegativeBalanceOccurrence>? Occurrences { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Plaid.OpenApiClient.Models.NegativeBalanceOccurrence> Occurrences { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Plaid.OpenApiClient.Models.NegativeBalanceInsights"/> and sets the default values.
        /// </summary>
        public NegativeBalanceInsights()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Plaid.OpenApiClient.Models.NegativeBalanceInsights"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Plaid.OpenApiClient.Models.NegativeBalanceInsights CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Plaid.OpenApiClient.Models.NegativeBalanceInsights();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "days_since_last_occurrence", n => { DaysSinceLastOccurrence = n.GetIntValue(); } },
                { "days_with_negative_balance", n => { DaysWithNegativeBalance = n.GetIntValue(); } },
                { "minimum_balance", n => { MinimumBalance = n.GetObjectValue<global::Soenneker.Plaid.OpenApiClient.Models.AmountWithCurrency>(global::Soenneker.Plaid.OpenApiClient.Models.AmountWithCurrency.CreateFromDiscriminatorValue); } },
                { "occurrences", n => { Occurrences = n.GetCollectionOfObjectValues<global::Soenneker.Plaid.OpenApiClient.Models.NegativeBalanceOccurrence>(global::Soenneker.Plaid.OpenApiClient.Models.NegativeBalanceOccurrence.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("days_since_last_occurrence", DaysSinceLastOccurrence);
            writer.WriteIntValue("days_with_negative_balance", DaysWithNegativeBalance);
            writer.WriteObjectValue<global::Soenneker.Plaid.OpenApiClient.Models.AmountWithCurrency>("minimum_balance", MinimumBalance);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Plaid.OpenApiClient.Models.NegativeBalanceOccurrence>("occurrences", Occurrences);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
