// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Plaid.OpenApiClient.Models
{
    /// <summary>The status of the addendum to the Plaid MSA (&quot;flowdown&quot;) for the end customer.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum PartnerEndCustomerFlowdownStatus
    {
        [EnumMember(Value = "NOT_STARTED")]
        #pragma warning disable CS1591
        NOT_STARTED,
        #pragma warning restore CS1591
        [EnumMember(Value = "IN_REVIEW")]
        #pragma warning disable CS1591
        IN_REVIEW,
        #pragma warning restore CS1591
        [EnumMember(Value = "NEGOTIATION")]
        #pragma warning disable CS1591
        NEGOTIATION,
        #pragma warning restore CS1591
        [EnumMember(Value = "COMPLETE")]
        #pragma warning disable CS1591
        COMPLETE,
        #pragma warning restore CS1591
    }
}
