// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Plaid.OpenApiClient.Models
{
    /// <summary>Indicates which version of the personal finance category taxonomy is being used. [View PFCv2 and PFCv1 taxonomies](https://plaid.com/documents/pfc-taxonomy-all.csv).If you enabled Transactions or Enrich before December 2025 you will receive the `v1` taxonomy by default and may request `v2` by explicitly setting this field to `v2` in the request.If you enabled Transactions or Enrich on or after December 2025, you may only receive the `v2` taxonomy.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum PersonalFinanceCategoryVersion
    {
        [EnumMember(Value = "v1")]
        #pragma warning disable CS1591
        V1,
        #pragma warning restore CS1591
        [EnumMember(Value = "v2")]
        #pragma warning disable CS1591
        V2,
        #pragma warning restore CS1591
    }
}
