// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Plaid.OpenApiClient.Models
{
    /// <summary>
    /// ProcessorSignalDecisionReportRequest defines the request schema for `/processor/signal/decision/report`
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ProcessorSignalDecisionReportRequest : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The amount (in USD) made available to your customers instantly following the debit transaction. It could be a partial amount of the requested transaction (example: 102.05).</summary>
        public double? AmountInstantlyAvailable { get; set; }
        /// <summary>Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header or as part of a request body.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ClientId { get; set; }
#nullable restore
#else
        public string ClientId { get; set; }
#endif
        /// <summary>Must be the same as the `client_transaction_id` supplied when calling `/signal/evaluate`</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ClientTransactionId { get; set; }
#nullable restore
#else
        public string ClientTransactionId { get; set; }
#endif
        /// <summary>The actual number of days (hold time) since the ACH debit transaction that you wait before making funds available to your customers. The holding time could affect the ACH return rate.For example, use 0 if you make funds available to your customers instantly or the same day following the debit transaction, or 1 if you make funds available the next day following the debit initialization.</summary>
        public int? DaysFundsOnHold { get; set; }
        /// <summary>The payment decision from the risk assessment.`APPROVE`: approve the transaction without requiring further actions from your customers. For example, use this field if you are placing a standard hold for all the approved transactions before making funds available to your customers. You should also use this field if you decide to accelerate the fund availability for your customers.`REVIEW`: the transaction requires manual review`REJECT`: reject the transaction`TAKE_OTHER_RISK_MEASURES`: for example, placing a longer hold on funds than those approved transactions or introducing customer frictions such as step-up verification/authentication`NOT_EVALUATED`: if only logging the results without using them</summary>
        public global::Soenneker.Plaid.OpenApiClient.Models.SignalDecisionOutcome? DecisionOutcome { get; set; }
        /// <summary>`true` if the ACH transaction was initiated, `false` otherwise.This field must be returned as a boolean. If formatted incorrectly, this will result in an [`INVALID_FIELD`](https://plaid.com/docs/errors/invalid-request/#invalid_field) error.</summary>
        public bool? Initiated { get; set; }
        /// <summary>The payment method to complete the transaction after the risk assessment. It may be different from the default payment method.`SAME_DAY_ACH`: Same Day ACH by Nacha. The debit transaction is processed and settled on the same day.`STANDARD_ACH`: Standard ACH by Nacha.`MULTIPLE_PAYMENT_METHODS`: if there is no default debit rail or there are multiple payment methods.</summary>
        public global::Soenneker.Plaid.OpenApiClient.Models.SignalPaymentMethod? PaymentMethod { get; set; }
        /// <summary>The processor token obtained from the Plaid integration partner. Processor tokens are in the format: `processor-&lt;environment&gt;-&lt;identifier&gt;`</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ProcessorToken { get; set; }
#nullable restore
#else
        public string ProcessorToken { get; set; }
#endif
        /// <summary>Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part of a request body.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Secret { get; set; }
#nullable restore
#else
        public string Secret { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Plaid.OpenApiClient.Models.ProcessorSignalDecisionReportRequest"/> and sets the default values.
        /// </summary>
        public ProcessorSignalDecisionReportRequest()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Plaid.OpenApiClient.Models.ProcessorSignalDecisionReportRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Plaid.OpenApiClient.Models.ProcessorSignalDecisionReportRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Plaid.OpenApiClient.Models.ProcessorSignalDecisionReportRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "amount_instantly_available", n => { AmountInstantlyAvailable = n.GetDoubleValue(); } },
                { "client_id", n => { ClientId = n.GetStringValue(); } },
                { "client_transaction_id", n => { ClientTransactionId = n.GetStringValue(); } },
                { "days_funds_on_hold", n => { DaysFundsOnHold = n.GetIntValue(); } },
                { "decision_outcome", n => { DecisionOutcome = n.GetEnumValue<global::Soenneker.Plaid.OpenApiClient.Models.SignalDecisionOutcome>(); } },
                { "initiated", n => { Initiated = n.GetBoolValue(); } },
                { "payment_method", n => { PaymentMethod = n.GetEnumValue<global::Soenneker.Plaid.OpenApiClient.Models.SignalPaymentMethod>(); } },
                { "processor_token", n => { ProcessorToken = n.GetStringValue(); } },
                { "secret", n => { Secret = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDoubleValue("amount_instantly_available", AmountInstantlyAvailable);
            writer.WriteStringValue("client_id", ClientId);
            writer.WriteStringValue("client_transaction_id", ClientTransactionId);
            writer.WriteIntValue("days_funds_on_hold", DaysFundsOnHold);
            writer.WriteEnumValue<global::Soenneker.Plaid.OpenApiClient.Models.SignalDecisionOutcome>("decision_outcome", DecisionOutcome);
            writer.WriteBoolValue("initiated", Initiated);
            writer.WriteEnumValue<global::Soenneker.Plaid.OpenApiClient.Models.SignalPaymentMethod>("payment_method", PaymentMethod);
            writer.WriteStringValue("processor_token", ProcessorToken);
            writer.WriteStringValue("secret", Secret);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
