// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Plaid.OpenApiClient.Models
{
    /// <summary>
    /// Risk indicators focus on providing signal on the possibility of a borrower defaulting on their loan repayments by providing data points related to its payment behavior, debt, and other relevant financial information, helping lenders gauge the level of risk involved in a certain operation.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class RiskIndicators : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Insights into bank penalties and fees, including overdraft fees, NSF fees, and other bank-imposed charges.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Plaid.OpenApiClient.Models.BankPenaltiesIndicators? BankPenalties { get; set; }
#nullable restore
#else
        public global::Soenneker.Plaid.OpenApiClient.Models.BankPenaltiesIndicators BankPenalties { get; set; }
#endif
        /// <summary>Insights into gambling-related transactions, including frequency, amounts, and top merchants.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Plaid.OpenApiClient.Models.GamblingIndicators? Gambling { get; set; }
#nullable restore
#else
        public global::Soenneker.Plaid.OpenApiClient.Models.GamblingIndicators Gambling { get; set; }
#endif
        /// <summary>Insights into loan disbursement transactions received by the user, tracking incoming funds from loan providers.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Plaid.OpenApiClient.Models.LoanDisbursementsIndicators? LoanDisbursements { get; set; }
#nullable restore
#else
        public global::Soenneker.Plaid.OpenApiClient.Models.LoanDisbursementsIndicators LoanDisbursements { get; set; }
#endif
        /// <summary>Insights into loan payment transactions made by the user, tracking outgoing payments to loan providers.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Plaid.OpenApiClient.Models.LoanPaymentsIndicators? LoanPayments { get; set; }
#nullable restore
#else
        public global::Soenneker.Plaid.OpenApiClient.Models.LoanPaymentsIndicators LoanPayments { get; set; }
#endif
        /// <summary>Insights into negative balance occurrences, including frequency, duration, and minimum balance details.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Plaid.OpenApiClient.Models.NegativeBalanceInsights? NegativeBalance { get; set; }
#nullable restore
#else
        public global::Soenneker.Plaid.OpenApiClient.Models.NegativeBalanceInsights NegativeBalance { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Plaid.OpenApiClient.Models.RiskIndicators"/> and sets the default values.
        /// </summary>
        public RiskIndicators()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Plaid.OpenApiClient.Models.RiskIndicators"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Plaid.OpenApiClient.Models.RiskIndicators CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Plaid.OpenApiClient.Models.RiskIndicators();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "bank_penalties", n => { BankPenalties = n.GetObjectValue<global::Soenneker.Plaid.OpenApiClient.Models.BankPenaltiesIndicators>(global::Soenneker.Plaid.OpenApiClient.Models.BankPenaltiesIndicators.CreateFromDiscriminatorValue); } },
                { "gambling", n => { Gambling = n.GetObjectValue<global::Soenneker.Plaid.OpenApiClient.Models.GamblingIndicators>(global::Soenneker.Plaid.OpenApiClient.Models.GamblingIndicators.CreateFromDiscriminatorValue); } },
                { "loan_disbursements", n => { LoanDisbursements = n.GetObjectValue<global::Soenneker.Plaid.OpenApiClient.Models.LoanDisbursementsIndicators>(global::Soenneker.Plaid.OpenApiClient.Models.LoanDisbursementsIndicators.CreateFromDiscriminatorValue); } },
                { "loan_payments", n => { LoanPayments = n.GetObjectValue<global::Soenneker.Plaid.OpenApiClient.Models.LoanPaymentsIndicators>(global::Soenneker.Plaid.OpenApiClient.Models.LoanPaymentsIndicators.CreateFromDiscriminatorValue); } },
                { "negative_balance", n => { NegativeBalance = n.GetObjectValue<global::Soenneker.Plaid.OpenApiClient.Models.NegativeBalanceInsights>(global::Soenneker.Plaid.OpenApiClient.Models.NegativeBalanceInsights.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Plaid.OpenApiClient.Models.BankPenaltiesIndicators>("bank_penalties", BankPenalties);
            writer.WriteObjectValue<global::Soenneker.Plaid.OpenApiClient.Models.GamblingIndicators>("gambling", Gambling);
            writer.WriteObjectValue<global::Soenneker.Plaid.OpenApiClient.Models.LoanDisbursementsIndicators>("loan_disbursements", LoanDisbursements);
            writer.WriteObjectValue<global::Soenneker.Plaid.OpenApiClient.Models.LoanPaymentsIndicators>("loan_payments", LoanPayments);
            writer.WriteObjectValue<global::Soenneker.Plaid.OpenApiClient.Models.NegativeBalanceInsights>("negative_balance", NegativeBalance);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
