// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Plaid.OpenApiClient.Models
{
    /// <summary>Status of a document for risk signal analysis</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum RiskSignalDocumentStatus
    {
        [EnumMember(Value = "PROCESSING")]
        #pragma warning disable CS1591
        PROCESSING,
        #pragma warning restore CS1591
        [EnumMember(Value = "PROCESSING_COMPLETE")]
        #pragma warning disable CS1591
        PROCESSING_COMPLETE,
        #pragma warning restore CS1591
        [EnumMember(Value = "PROCESSING_ERROR")]
        #pragma warning disable CS1591
        PROCESSING_ERROR,
        #pragma warning restore CS1591
        [EnumMember(Value = "PASSWORD_PROTECTED")]
        #pragma warning disable CS1591
        PASSWORD_PROTECTED,
        #pragma warning restore CS1591
        [EnumMember(Value = "VIRUS_DETECTED")]
        #pragma warning disable CS1591
        VIRUS_DETECTED,
        #pragma warning restore CS1591
    }
}
