// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Plaid.OpenApiClient.Models
{
    /// <summary>
    /// Result summary object capturing abuse signals related to `identity abuse`, e.g. stolen and synthetic identity fraud. These attributes are only available for US identities and some signals may not be available depending on what information was collected.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class RiskCheckIdentityAbuseSignals : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Field containing the data used in determining the outcome of the stolen identity risk check.Contains the following fields:`score` - A score from 0 to 100 indicating the likelihood that the user is a stolen identity.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Plaid.OpenApiClient.Models.RiskCheckStolenIdentity? StolenIdentity { get; set; }
#nullable restore
#else
        public global::Soenneker.Plaid.OpenApiClient.Models.RiskCheckStolenIdentity StolenIdentity { get; set; }
#endif
        /// <summary>Field containing the data used in determining the outcome of the synthetic identity risk check.Contains the following fields:`score` - A score from 0 to 100 indicating the likelihood that the user is a synthetic identity.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Plaid.OpenApiClient.Models.RiskCheckSyntheticIdentity? SyntheticIdentity { get; set; }
#nullable restore
#else
        public global::Soenneker.Plaid.OpenApiClient.Models.RiskCheckSyntheticIdentity SyntheticIdentity { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Plaid.OpenApiClient.Models.RiskCheckIdentityAbuseSignals"/> and sets the default values.
        /// </summary>
        public RiskCheckIdentityAbuseSignals()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Plaid.OpenApiClient.Models.RiskCheckIdentityAbuseSignals"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Plaid.OpenApiClient.Models.RiskCheckIdentityAbuseSignals CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Plaid.OpenApiClient.Models.RiskCheckIdentityAbuseSignals();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "stolen_identity", n => { StolenIdentity = n.GetObjectValue<global::Soenneker.Plaid.OpenApiClient.Models.RiskCheckStolenIdentity>(global::Soenneker.Plaid.OpenApiClient.Models.RiskCheckStolenIdentity.CreateFromDiscriminatorValue); } },
                { "synthetic_identity", n => { SyntheticIdentity = n.GetObjectValue<global::Soenneker.Plaid.OpenApiClient.Models.RiskCheckSyntheticIdentity>(global::Soenneker.Plaid.OpenApiClient.Models.RiskCheckSyntheticIdentity.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Plaid.OpenApiClient.Models.RiskCheckStolenIdentity>("stolen_identity", StolenIdentity);
            writer.WriteObjectValue<global::Soenneker.Plaid.OpenApiClient.Models.RiskCheckSyntheticIdentity>("synthetic_identity", SyntheticIdentity);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
