// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Plaid.OpenApiClient.Models
{
    /// <summary>
    /// Field containing the data used in determining the outcome of the synthetic identity risk check.Contains the following fields:`score` - A score from 0 to 100 indicating the likelihood that the user is a synthetic identity.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class RiskCheckSyntheticIdentity : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Field containing the data used in determining the outcome of a synthetic fraud risk check.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Plaid.OpenApiClient.Models.SyntheticFraud? FirstPartySyntheticFraud { get; set; }
#nullable restore
#else
        public global::Soenneker.Plaid.OpenApiClient.Models.SyntheticFraud FirstPartySyntheticFraud { get; set; }
#endif
        /// <summary>Risk level for the given risk check type.</summary>
        public global::Soenneker.Plaid.OpenApiClient.Models.RiskLevel? RiskLevel { get; set; }
        /// <summary>A score from 0 to 100 indicating the likelihood that the user is a synthetic identity.</summary>
        public int? Score { get; set; }
        /// <summary>Field containing the data used in determining the outcome of a synthetic fraud risk check.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Plaid.OpenApiClient.Models.SyntheticFraud? ThirdPartySyntheticFraud { get; set; }
#nullable restore
#else
        public global::Soenneker.Plaid.OpenApiClient.Models.SyntheticFraud ThirdPartySyntheticFraud { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Plaid.OpenApiClient.Models.RiskCheckSyntheticIdentity"/> and sets the default values.
        /// </summary>
        public RiskCheckSyntheticIdentity()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Plaid.OpenApiClient.Models.RiskCheckSyntheticIdentity"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Plaid.OpenApiClient.Models.RiskCheckSyntheticIdentity CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Plaid.OpenApiClient.Models.RiskCheckSyntheticIdentity();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "first_party_synthetic_fraud", n => { FirstPartySyntheticFraud = n.GetObjectValue<global::Soenneker.Plaid.OpenApiClient.Models.SyntheticFraud>(global::Soenneker.Plaid.OpenApiClient.Models.SyntheticFraud.CreateFromDiscriminatorValue); } },
                { "risk_level", n => { RiskLevel = n.GetEnumValue<global::Soenneker.Plaid.OpenApiClient.Models.RiskLevel>(); } },
                { "score", n => { Score = n.GetIntValue(); } },
                { "third_party_synthetic_fraud", n => { ThirdPartySyntheticFraud = n.GetObjectValue<global::Soenneker.Plaid.OpenApiClient.Models.SyntheticFraud>(global::Soenneker.Plaid.OpenApiClient.Models.SyntheticFraud.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Plaid.OpenApiClient.Models.SyntheticFraud>("first_party_synthetic_fraud", FirstPartySyntheticFraud);
            writer.WriteEnumValue<global::Soenneker.Plaid.OpenApiClient.Models.RiskLevel>("risk_level", RiskLevel);
            writer.WriteIntValue("score", Score);
            writer.WriteObjectValue<global::Soenneker.Plaid.OpenApiClient.Models.SyntheticFraud>("third_party_synthetic_fraud", ThirdPartySyntheticFraud);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
