// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Plaid.OpenApiClient.Models
{
    /// <summary>
    /// Details about the transaction result after evaluation by the requested Ruleset. If a `ruleset_key` is not provided, for customers who began using Signal Transaction Scores before October 15, 2025, by default, this field will be omitted. To learn more, see [Signal Rules](https://plaid.com/docs/signal/signal-rules/).
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Ruleset : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The evaluated outcome for this transaction. This field is deprecated, use `result` or `triggered_rule_details.custom_action_key` instead.</summary>
        [Obsolete("")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Outcome { get; set; }
#nullable restore
#else
        public string Outcome { get; set; }
#endif
        /// <summary>The result of the rule that was triggered for this transaction.`ACCEPT`: Accept the transaction for processing.`REROUTE`: Reroute the transaction to a different payment method, as this transaction is too risky.`REVIEW`: Review the transaction before proceeding.</summary>
        public global::Soenneker.Plaid.OpenApiClient.Models.RuleResult? Result { get; set; }
        /// <summary>The key of the Ruleset used for this transaction.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RulesetKey { get; set; }
#nullable restore
#else
        public string RulesetKey { get; set; }
#endif
        /// <summary>Rules are run in numerical order. The first rule with a logic match is triggered. These are the details of that rule.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Plaid.OpenApiClient.Models.RuleDetails? TriggeredRuleDetails { get; set; }
#nullable restore
#else
        public global::Soenneker.Plaid.OpenApiClient.Models.RuleDetails TriggeredRuleDetails { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Plaid.OpenApiClient.Models.Ruleset"/> and sets the default values.
        /// </summary>
        public Ruleset()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Plaid.OpenApiClient.Models.Ruleset"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Plaid.OpenApiClient.Models.Ruleset CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Plaid.OpenApiClient.Models.Ruleset();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "outcome", n => { Outcome = n.GetStringValue(); } },
                { "result", n => { Result = n.GetEnumValue<global::Soenneker.Plaid.OpenApiClient.Models.RuleResult>(); } },
                { "ruleset_key", n => { RulesetKey = n.GetStringValue(); } },
                { "triggered_rule_details", n => { TriggeredRuleDetails = n.GetObjectValue<global::Soenneker.Plaid.OpenApiClient.Models.RuleDetails>(global::Soenneker.Plaid.OpenApiClient.Models.RuleDetails.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("outcome", Outcome);
            writer.WriteEnumValue<global::Soenneker.Plaid.OpenApiClient.Models.RuleResult>("result", Result);
            writer.WriteStringValue("ruleset_key", RulesetKey);
            writer.WriteObjectValue<global::Soenneker.Plaid.OpenApiClient.Models.RuleDetails>("triggered_rule_details", TriggeredRuleDetails);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
