// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Plaid.OpenApiClient.Models
{
    /// <summary>The webhook codes this endpoint can be used to test</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum SandboxBankIncomeWebhookFireRequestWebhookCode
    {
        [EnumMember(Value = "BANK_INCOME_REFRESH_UPDATE")]
        #pragma warning disable CS1591
        BANK_INCOME_REFRESH_UPDATE,
        #pragma warning restore CS1591
        [EnumMember(Value = "BANK_INCOME_REFRESH_COMPLETE")]
        #pragma warning disable CS1591
        BANK_INCOME_REFRESH_COMPLETE,
        #pragma warning restore CS1591
    }
}
