// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Plaid.OpenApiClient.Models
{
    /// <summary>`VERIFICATION_STATUS_PROCESSING_COMPLETE`: The income verification status processing has completed. If the user uploaded multiple documents, this webhook will fire when all documents have finished processing. Call the `/income/verification/paystubs/get` endpoint and check the document metadata to see which documents were successfully parsed.`VERIFICATION_STATUS_PROCESSING_FAILED`: A failure occurred when attempting to process the verification documentation.`VERIFICATION_STATUS_PENDING_APPROVAL`: (deprecated) The income verification has been sent to the user for review.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum SandboxIncomeFireWebhookRequest_verification_status
    {
        [EnumMember(Value = "VERIFICATION_STATUS_PROCESSING_COMPLETE")]
        #pragma warning disable CS1591
        VERIFICATION_STATUS_PROCESSING_COMPLETE,
        #pragma warning restore CS1591
        [EnumMember(Value = "VERIFICATION_STATUS_PROCESSING_FAILED")]
        #pragma warning disable CS1591
        VERIFICATION_STATUS_PROCESSING_FAILED,
        #pragma warning restore CS1591
        [EnumMember(Value = "VERIFICATION_STATUS_PENDING_APPROVAL")]
        #pragma warning disable CS1591
        VERIFICATION_STATUS_PENDING_APPROVAL,
        #pragma warning restore CS1591
    }
}
