// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Plaid.OpenApiClient.Models
{
    /// <summary>
    /// Contains details about a student loan account
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class StudentLoan : IAdditionalDataHolder, IParsable
    {
        /// <summary>The ID of the account that this liability belongs to. Each account can only contain one liability.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AccountId { get; set; }
#nullable restore
#else
        public string AccountId { get; set; }
#endif
        /// <summary>The account number of the loan. For some institutions, this may be a masked version of the number (e.g., the last 4 digits instead of the entire number).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AccountNumber { get; set; }
#nullable restore
#else
        public string AccountNumber { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The dates on which loaned funds were disbursed or will be disbursed. These are often in the past. Dates are returned in an [ISO 8601](https://wikipedia.org/wiki/ISO_8601) format (YYYY-MM-DD).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<Date?>? DisbursementDates { get; set; }
#nullable restore
#else
        public List<Date?> DisbursementDates { get; set; }
#endif
        /// <summary>The date when the student loan is expected to be paid off. Availability for this field is limited. Dates are returned in an [ISO 8601](https://wikipedia.org/wiki/ISO_8601) format (YYYY-MM-DD).</summary>
        public Date? ExpectedPayoffDate { get; set; }
        /// <summary>The guarantor of the student loan.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Guarantor { get; set; }
#nullable restore
#else
        public string Guarantor { get; set; }
#endif
        /// <summary>The interest rate on the loan as a percentage.</summary>
        public double? InterestRatePercentage { get; set; }
        /// <summary>`true` if a payment is currently overdue. Availability for this field is limited.</summary>
        public bool? IsOverdue { get; set; }
        /// <summary>The amount of the last payment.</summary>
        public double? LastPaymentAmount { get; set; }
        /// <summary>The date of the last payment. Dates are returned in an [ISO 8601](https://wikipedia.org/wiki/ISO_8601) format (YYYY-MM-DD).</summary>
        public Date? LastPaymentDate { get; set; }
        /// <summary>The total amount owed as of the last statement issued</summary>
        public double? LastStatementBalance { get; set; }
        /// <summary>The date of the last statement. Dates are returned in an [ISO 8601](https://wikipedia.org/wiki/ISO_8601) format (YYYY-MM-DD).</summary>
        public Date? LastStatementIssueDate { get; set; }
        /// <summary>The type of loan, e.g., &quot;Consolidation Loans&quot;.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LoanName { get; set; }
#nullable restore
#else
        public string LoanName { get; set; }
#endif
        /// <summary>An object representing the status of the student loan</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Plaid.OpenApiClient.Models.StudentLoanStatus? LoanStatus { get; set; }
#nullable restore
#else
        public global::Soenneker.Plaid.OpenApiClient.Models.StudentLoanStatus LoanStatus { get; set; }
#endif
        /// <summary>The minimum payment due for the next billing cycle. There are some exceptions:Some institutions require a minimum payment across all loans associated with an account number. Our API presents that same minimum payment amount on each loan. The institutions that do this are: Great Lakes ( `ins_116861`), Firstmark (`ins_116295`), Commonbond Firstmark Services (`ins_116950`), Granite State (`ins_116308`), and Oklahoma Student Loan Authority (`ins_116945`).Firstmark (`ins_116295` ) and Navient (`ins_116248`) will display as $0 if there is an autopay program in effect.</summary>
        public double? MinimumPaymentAmount { get; set; }
        /// <summary>The due date for the next payment. The due date is `null` if a payment is not expected. A payment is not expected if `loan_status.type` is `deferment`, `in_school`, `consolidated`, `paid in full`, or `transferred`. Dates are returned in an [ISO 8601](https://wikipedia.org/wiki/ISO_8601) format (YYYY-MM-DD).</summary>
        public Date? NextPaymentDueDate { get; set; }
        /// <summary>The date on which the loan was initially lent. Dates are returned in an [ISO 8601](https://wikipedia.org/wiki/ISO_8601) format (YYYY-MM-DD).</summary>
        public Date? OriginationDate { get; set; }
        /// <summary>The original principal balance of the loan.</summary>
        public double? OriginationPrincipalAmount { get; set; }
        /// <summary>The total dollar amount of the accrued interest balance. For Sallie Mae ( `ins_116944`), this amount is included in the current balance of the loan, so this field will return as `null`.</summary>
        public double? OutstandingInterestAmount { get; set; }
        /// <summary>The relevant account number that should be used to reference this loan for payments. In the majority of cases, `payment_reference_number` will match `account_number,` but in some institutions, such as Great Lakes (`ins_116861`), it will be different.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PaymentReferenceNumber { get; set; }
#nullable restore
#else
        public string PaymentReferenceNumber { get; set; }
#endif
        /// <summary>Information about the student&apos;s eligibility in the Public Service Loan Forgiveness program. This is only returned if the institution is FedLoan (`ins_116527`). Since FedLoan no longer services student loans, this field is no longer returned. </summary>
        [Obsolete("")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Plaid.OpenApiClient.Models.PSLFStatus? PslfStatus { get; set; }
#nullable restore
#else
        public global::Soenneker.Plaid.OpenApiClient.Models.PSLFStatus PslfStatus { get; set; }
#endif
        /// <summary>An object representing the repayment plan for the student loan</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Plaid.OpenApiClient.Models.StudentRepaymentPlan? RepaymentPlan { get; set; }
#nullable restore
#else
        public global::Soenneker.Plaid.OpenApiClient.Models.StudentRepaymentPlan RepaymentPlan { get; set; }
#endif
        /// <summary>The sequence number of the student loan. Heartland ECSI (`ins_116948`) does not make this field available.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SequenceNumber { get; set; }
#nullable restore
#else
        public string SequenceNumber { get; set; }
#endif
        /// <summary>The address of the student loan servicer. This is generally the remittance address to which payments should be sent.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Plaid.OpenApiClient.Models.ServicerAddressData? ServicerAddress { get; set; }
#nullable restore
#else
        public global::Soenneker.Plaid.OpenApiClient.Models.ServicerAddressData ServicerAddress { get; set; }
#endif
        /// <summary>The year to date (YTD) interest paid. Availability for this field is limited.</summary>
        public double? YtdInterestPaid { get; set; }
        /// <summary>The year to date (YTD) principal paid. Availability for this field is limited.</summary>
        public double? YtdPrincipalPaid { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Plaid.OpenApiClient.Models.StudentLoan"/> and sets the default values.
        /// </summary>
        public StudentLoan()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Plaid.OpenApiClient.Models.StudentLoan"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Plaid.OpenApiClient.Models.StudentLoan CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Plaid.OpenApiClient.Models.StudentLoan();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "account_id", n => { AccountId = n.GetStringValue(); } },
                { "account_number", n => { AccountNumber = n.GetStringValue(); } },
                { "disbursement_dates", n => { DisbursementDates = n.GetCollectionOfPrimitiveValues<Date?>()?.AsList(); } },
                { "expected_payoff_date", n => { ExpectedPayoffDate = n.GetDateValue(); } },
                { "guarantor", n => { Guarantor = n.GetStringValue(); } },
                { "interest_rate_percentage", n => { InterestRatePercentage = n.GetDoubleValue(); } },
                { "is_overdue", n => { IsOverdue = n.GetBoolValue(); } },
                { "last_payment_amount", n => { LastPaymentAmount = n.GetDoubleValue(); } },
                { "last_payment_date", n => { LastPaymentDate = n.GetDateValue(); } },
                { "last_statement_balance", n => { LastStatementBalance = n.GetDoubleValue(); } },
                { "last_statement_issue_date", n => { LastStatementIssueDate = n.GetDateValue(); } },
                { "loan_name", n => { LoanName = n.GetStringValue(); } },
                { "loan_status", n => { LoanStatus = n.GetObjectValue<global::Soenneker.Plaid.OpenApiClient.Models.StudentLoanStatus>(global::Soenneker.Plaid.OpenApiClient.Models.StudentLoanStatus.CreateFromDiscriminatorValue); } },
                { "minimum_payment_amount", n => { MinimumPaymentAmount = n.GetDoubleValue(); } },
                { "next_payment_due_date", n => { NextPaymentDueDate = n.GetDateValue(); } },
                { "origination_date", n => { OriginationDate = n.GetDateValue(); } },
                { "origination_principal_amount", n => { OriginationPrincipalAmount = n.GetDoubleValue(); } },
                { "outstanding_interest_amount", n => { OutstandingInterestAmount = n.GetDoubleValue(); } },
                { "payment_reference_number", n => { PaymentReferenceNumber = n.GetStringValue(); } },
                { "pslf_status", n => { PslfStatus = n.GetObjectValue<global::Soenneker.Plaid.OpenApiClient.Models.PSLFStatus>(global::Soenneker.Plaid.OpenApiClient.Models.PSLFStatus.CreateFromDiscriminatorValue); } },
                { "repayment_plan", n => { RepaymentPlan = n.GetObjectValue<global::Soenneker.Plaid.OpenApiClient.Models.StudentRepaymentPlan>(global::Soenneker.Plaid.OpenApiClient.Models.StudentRepaymentPlan.CreateFromDiscriminatorValue); } },
                { "sequence_number", n => { SequenceNumber = n.GetStringValue(); } },
                { "servicer_address", n => { ServicerAddress = n.GetObjectValue<global::Soenneker.Plaid.OpenApiClient.Models.ServicerAddressData>(global::Soenneker.Plaid.OpenApiClient.Models.ServicerAddressData.CreateFromDiscriminatorValue); } },
                { "ytd_interest_paid", n => { YtdInterestPaid = n.GetDoubleValue(); } },
                { "ytd_principal_paid", n => { YtdPrincipalPaid = n.GetDoubleValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("account_id", AccountId);
            writer.WriteStringValue("account_number", AccountNumber);
            writer.WriteCollectionOfPrimitiveValues<Date?>("disbursement_dates", DisbursementDates);
            writer.WriteDateValue("expected_payoff_date", ExpectedPayoffDate);
            writer.WriteStringValue("guarantor", Guarantor);
            writer.WriteDoubleValue("interest_rate_percentage", InterestRatePercentage);
            writer.WriteBoolValue("is_overdue", IsOverdue);
            writer.WriteDoubleValue("last_payment_amount", LastPaymentAmount);
            writer.WriteDateValue("last_payment_date", LastPaymentDate);
            writer.WriteDoubleValue("last_statement_balance", LastStatementBalance);
            writer.WriteDateValue("last_statement_issue_date", LastStatementIssueDate);
            writer.WriteStringValue("loan_name", LoanName);
            writer.WriteObjectValue<global::Soenneker.Plaid.OpenApiClient.Models.StudentLoanStatus>("loan_status", LoanStatus);
            writer.WriteDoubleValue("minimum_payment_amount", MinimumPaymentAmount);
            writer.WriteDateValue("next_payment_due_date", NextPaymentDueDate);
            writer.WriteDateValue("origination_date", OriginationDate);
            writer.WriteDoubleValue("origination_principal_amount", OriginationPrincipalAmount);
            writer.WriteDoubleValue("outstanding_interest_amount", OutstandingInterestAmount);
            writer.WriteStringValue("payment_reference_number", PaymentReferenceNumber);
            writer.WriteObjectValue<global::Soenneker.Plaid.OpenApiClient.Models.PSLFStatus>("pslf_status", PslfStatus);
            writer.WriteObjectValue<global::Soenneker.Plaid.OpenApiClient.Models.StudentRepaymentPlan>("repayment_plan", RepaymentPlan);
            writer.WriteStringValue("sequence_number", SequenceNumber);
            writer.WriteObjectValue<global::Soenneker.Plaid.OpenApiClient.Models.ServicerAddressData>("servicer_address", ServicerAddress);
            writer.WriteDoubleValue("ytd_interest_paid", YtdInterestPaid);
            writer.WriteDoubleValue("ytd_principal_paid", YtdPrincipalPaid);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
