// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Plaid.OpenApiClient.Models
{
    /// <summary>Commonly used term to describe the line item.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum TotalCanonicalDescription
    {
        [EnumMember(Value = "BONUS")]
        #pragma warning disable CS1591
        BONUS,
        #pragma warning restore CS1591
        [EnumMember(Value = "COMMISSION")]
        #pragma warning disable CS1591
        COMMISSION,
        #pragma warning restore CS1591
        [EnumMember(Value = "OVERTIME")]
        #pragma warning disable CS1591
        OVERTIME,
        #pragma warning restore CS1591
        [EnumMember(Value = "PAID TIME OFF")]
        #pragma warning disable CS1591
        PAIDTIMEOFF,
        #pragma warning restore CS1591
        [EnumMember(Value = "REGULAR PAY")]
        #pragma warning disable CS1591
        REGULARPAY,
        #pragma warning restore CS1591
        [EnumMember(Value = "VACATION")]
        #pragma warning disable CS1591
        VACATION,
        #pragma warning restore CS1591
        [EnumMember(Value = "EMPLOYEE MEDICARE")]
        #pragma warning disable CS1591
        EMPLOYEEMEDICARE,
        #pragma warning restore CS1591
        [EnumMember(Value = "FICA")]
        #pragma warning disable CS1591
        FICA,
        #pragma warning restore CS1591
        [EnumMember(Value = "SOCIAL SECURITY EMPLOYEE TAX")]
        #pragma warning disable CS1591
        SOCIALSECURITYEMPLOYEETAX,
        #pragma warning restore CS1591
        [EnumMember(Value = "MEDICAL")]
        #pragma warning disable CS1591
        MEDICAL,
        #pragma warning restore CS1591
        [EnumMember(Value = "VISION")]
        #pragma warning disable CS1591
        VISION,
        #pragma warning restore CS1591
        [EnumMember(Value = "DENTAL")]
        #pragma warning disable CS1591
        DENTAL,
        #pragma warning restore CS1591
        [EnumMember(Value = "NET PAY")]
        #pragma warning disable CS1591
        NETPAY,
        #pragma warning restore CS1591
        [EnumMember(Value = "TAXES")]
        #pragma warning disable CS1591
        TAXES,
        #pragma warning restore CS1591
        [EnumMember(Value = "NOT_FOUND")]
        #pragma warning disable CS1591
        NOT_FOUND,
        #pragma warning restore CS1591
        [EnumMember(Value = "OTHER")]
        #pragma warning disable CS1591
        OTHER,
        #pragma warning restore CS1591
        [EnumMember(Value = "openapi-json-null-sentinel-value-2BF93600-0FE4-4250-987A-E5DDB203E464")]
        #pragma warning disable CS1591
        OpenapiJsonNullSentinelValue2BF936000FE44250987AE5DDB203E464,
        #pragma warning restore CS1591
    }
}
