// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Plaid.OpenApiClient.Models
{
    /// <summary>Originator’s diligence status.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum TransferDiligenceStatus
    {
        [EnumMember(Value = "not_submitted")]
        #pragma warning disable CS1591
        Not_submitted,
        #pragma warning restore CS1591
        [EnumMember(Value = "submitted")]
        #pragma warning disable CS1591
        Submitted,
        #pragma warning restore CS1591
        [EnumMember(Value = "under_review")]
        #pragma warning disable CS1591
        Under_review,
        #pragma warning restore CS1591
        [EnumMember(Value = "approved")]
        #pragma warning disable CS1591
        Approved,
        #pragma warning restore CS1591
        [EnumMember(Value = "denied")]
        #pragma warning disable CS1591
        Denied,
        #pragma warning restore CS1591
        [EnumMember(Value = "more_information_required")]
        #pragma warning disable CS1591
        More_information_required,
        #pragma warning restore CS1591
    }
}
