// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Plaid.OpenApiClient.Models
{
    /// <summary>Indicates whether the transfer is guaranteed by Plaid (Guarantee customers only). This field will contain either `GUARANTEED` or `NOT_GUARANTEED` indicating whether Plaid will guarantee the transfer.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum TransferAuthorizationGuaranteeDecision
    {
        [EnumMember(Value = "GUARANTEED")]
        #pragma warning disable CS1591
        GUARANTEED,
        #pragma warning restore CS1591
        [EnumMember(Value = "NOT_GUARANTEED")]
        #pragma warning disable CS1591
        NOT_GUARANTEED,
        #pragma warning restore CS1591
    }
}
