// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Plaid.OpenApiClient.Models
{
    /// <summary>Networks eligible for recurring transfers.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum TransferRecurringNetwork
    {
        [EnumMember(Value = "ach")]
        #pragma warning disable CS1591
        Ach,
        #pragma warning restore CS1591
        [EnumMember(Value = "same-day-ach")]
        #pragma warning disable CS1591
        SameDayAch,
        #pragma warning restore CS1591
        [EnumMember(Value = "rtp")]
        #pragma warning disable CS1591
        Rtp,
        #pragma warning restore CS1591
    }
}
