// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Plaid.OpenApiClient.Models
{
    /// <summary>
    /// TransactionsRulesCreateRequest defines the request schema for `beta/transactions/rules/v1/create`
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class TransactionsRulesCreateRequest : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header or as part of a request body.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ClientId { get; set; }
#nullable restore
#else
        public string ClientId { get; set; }
#endif
        /// <summary>A unique ID representing the end user. This ID is used to associate rules with a specific user.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ClientUserId { get; set; }
#nullable restore
#else
        public string ClientUserId { get; set; }
#endif
        /// <summary>A personal finance detailed category.See the [taxonomy csv file](https://plaid.com/documents/pfc-taxonomy-all.csv) for a full list of personal finance categories.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PfcDetailedCategory { get; set; }
#nullable restore
#else
        public string PfcDetailedCategory { get; set; }
#endif
        /// <summary>A personal finance primary category.See the [taxonomy csv file](https://plaid.com/documents/pfc-taxonomy-all.csv) for a full list of personal finance categories.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PfcPrimaryCategory { get; set; }
#nullable restore
#else
        public string PfcPrimaryCategory { get; set; }
#endif
        /// <summary>A representation of transactions rule details.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Plaid.OpenApiClient.Models.TransactionsRuleDetails? RuleDetails { get; set; }
#nullable restore
#else
        public global::Soenneker.Plaid.OpenApiClient.Models.TransactionsRuleDetails RuleDetails { get; set; }
#endif
        /// <summary>Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part of a request body.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Secret { get; set; }
#nullable restore
#else
        public string Secret { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Plaid.OpenApiClient.Models.TransactionsRulesCreateRequest"/> and sets the default values.
        /// </summary>
        public TransactionsRulesCreateRequest()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Plaid.OpenApiClient.Models.TransactionsRulesCreateRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Plaid.OpenApiClient.Models.TransactionsRulesCreateRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Plaid.OpenApiClient.Models.TransactionsRulesCreateRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "client_id", n => { ClientId = n.GetStringValue(); } },
                { "client_user_id", n => { ClientUserId = n.GetStringValue(); } },
                { "pfc_detailed_category", n => { PfcDetailedCategory = n.GetStringValue(); } },
                { "pfc_primary_category", n => { PfcPrimaryCategory = n.GetStringValue(); } },
                { "rule_details", n => { RuleDetails = n.GetObjectValue<global::Soenneker.Plaid.OpenApiClient.Models.TransactionsRuleDetails>(global::Soenneker.Plaid.OpenApiClient.Models.TransactionsRuleDetails.CreateFromDiscriminatorValue); } },
                { "secret", n => { Secret = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("client_id", ClientId);
            writer.WriteStringValue("client_user_id", ClientUserId);
            writer.WriteStringValue("pfc_detailed_category", PfcDetailedCategory);
            writer.WriteStringValue("pfc_primary_category", PfcPrimaryCategory);
            writer.WriteObjectValue<global::Soenneker.Plaid.OpenApiClient.Models.TransactionsRuleDetails>("rule_details", RuleDetails);
            writer.WriteStringValue("secret", Secret);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
