// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Plaid.OpenApiClient.Models
{
    /// <summary>
    /// Defines the request schema for `/transfer/diligence/document/upload`
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class TransferDiligenceDocumentUploadRequest : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>A file to upload. The file size must be less than 20MB. Supported file extensions: .pdf.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public byte[]? File { get; set; }
#nullable restore
#else
        public byte[] File { get; set; }
#endif
        /// <summary>The Client ID of the originator whose document that you want to upload.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OriginatorClientId { get; set; }
#nullable restore
#else
        public string OriginatorClientId { get; set; }
#endif
        /// <summary>Specifies the purpose of the uploaded file.`&quot;DUE_DILIGENCE&quot;` - The transfer due diligence document of the originator.</summary>
        public global::Soenneker.Plaid.OpenApiClient.Models.TransferDocumentPurpose? Purpose { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Plaid.OpenApiClient.Models.TransferDiligenceDocumentUploadRequest"/> and sets the default values.
        /// </summary>
        public TransferDiligenceDocumentUploadRequest()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Plaid.OpenApiClient.Models.TransferDiligenceDocumentUploadRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Plaid.OpenApiClient.Models.TransferDiligenceDocumentUploadRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Plaid.OpenApiClient.Models.TransferDiligenceDocumentUploadRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "file", n => { File = n.GetByteArrayValue(); } },
                { "originator_client_id", n => { OriginatorClientId = n.GetStringValue(); } },
                { "purpose", n => { Purpose = n.GetEnumValue<global::Soenneker.Plaid.OpenApiClient.Models.TransferDocumentPurpose>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteByteArrayValue("file", File);
            writer.WriteStringValue("originator_client_id", OriginatorClientId);
            writer.WriteEnumValue<global::Soenneker.Plaid.OpenApiClient.Models.TransferDocumentPurpose>("purpose", Purpose);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
