// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Plaid.OpenApiClient.Models
{
    /// <summary>
    /// W2 is an object that represents income data taken from a W2 tax document.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class W2 : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Allocated tips.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AllocatedTips { get; set; }
#nullable restore
#else
        public string AllocatedTips { get; set; }
#endif
        /// <summary>The box_12 property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Plaid.OpenApiClient.Models.W2Box12>? Box12 { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Plaid.OpenApiClient.Models.W2Box12> Box12 { get; set; }
#endif
        /// <summary>Contents from box 9 on the W2.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Box9 { get; set; }
#nullable restore
#else
        public string Box9 { get; set; }
#endif
        /// <summary>Dependent care benefits.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DependentCareBenefits { get; set; }
#nullable restore
#else
        public string DependentCareBenefits { get; set; }
#endif
        /// <summary>Data about the employee.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Plaid.OpenApiClient.Models.Employee? Employee { get; set; }
#nullable restore
#else
        public global::Soenneker.Plaid.OpenApiClient.Models.Employee Employee { get; set; }
#endif
        /// <summary>Information about the employer on the paystub</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Plaid.OpenApiClient.Models.PaystubEmployer? Employer { get; set; }
#nullable restore
#else
        public global::Soenneker.Plaid.OpenApiClient.Models.PaystubEmployer Employer { get; set; }
#endif
        /// <summary>An employee identification number or EIN.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? EmployerIdNumber { get; set; }
#nullable restore
#else
        public string EmployerIdNumber { get; set; }
#endif
        /// <summary>Federal income tax withheld for the tax year.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FederalIncomeTaxWithheld { get; set; }
#nullable restore
#else
        public string FederalIncomeTaxWithheld { get; set; }
#endif
        /// <summary>Medicare tax withheld for the tax year.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MedicareTaxWithheld { get; set; }
#nullable restore
#else
        public string MedicareTaxWithheld { get; set; }
#endif
        /// <summary>Wages and tips from medicare.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MedicareWagesAndTips { get; set; }
#nullable restore
#else
        public string MedicareWagesAndTips { get; set; }
#endif
        /// <summary>Nonqualified plans.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? NonqualifiedPlans { get; set; }
#nullable restore
#else
        public string NonqualifiedPlans { get; set; }
#endif
        /// <summary>Other.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Other { get; set; }
#nullable restore
#else
        public string Other { get; set; }
#endif
        /// <summary>Retirement plan.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RetirementPlan { get; set; }
#nullable restore
#else
        public string RetirementPlan { get; set; }
#endif
        /// <summary>Social security tax withheld for the tax year.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SocialSecurityTaxWithheld { get; set; }
#nullable restore
#else
        public string SocialSecurityTaxWithheld { get; set; }
#endif
        /// <summary>Tips from social security.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SocialSecurityTips { get; set; }
#nullable restore
#else
        public string SocialSecurityTips { get; set; }
#endif
        /// <summary>Wages from social security.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SocialSecurityWages { get; set; }
#nullable restore
#else
        public string SocialSecurityWages { get; set; }
#endif
        /// <summary>The state_and_local_wages property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Plaid.OpenApiClient.Models.W2StateAndLocalWages>? StateAndLocalWages { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Plaid.OpenApiClient.Models.W2StateAndLocalWages> StateAndLocalWages { get; set; }
#endif
        /// <summary>Statutory employee.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? StatutoryEmployee { get; set; }
#nullable restore
#else
        public string StatutoryEmployee { get; set; }
#endif
        /// <summary>The tax year of the W2 document.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TaxYear { get; set; }
#nullable restore
#else
        public string TaxYear { get; set; }
#endif
        /// <summary>Third party sick pay.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ThirdPartySickPay { get; set; }
#nullable restore
#else
        public string ThirdPartySickPay { get; set; }
#endif
        /// <summary>Wages from tips and other compensation.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? WagesTipsOtherComp { get; set; }
#nullable restore
#else
        public string WagesTipsOtherComp { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Plaid.OpenApiClient.Models.W2"/> and sets the default values.
        /// </summary>
        public W2()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Plaid.OpenApiClient.Models.W2"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Plaid.OpenApiClient.Models.W2 CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Plaid.OpenApiClient.Models.W2();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "allocated_tips", n => { AllocatedTips = n.GetStringValue(); } },
                { "box_12", n => { Box12 = n.GetCollectionOfObjectValues<global::Soenneker.Plaid.OpenApiClient.Models.W2Box12>(global::Soenneker.Plaid.OpenApiClient.Models.W2Box12.CreateFromDiscriminatorValue)?.AsList(); } },
                { "box_9", n => { Box9 = n.GetStringValue(); } },
                { "dependent_care_benefits", n => { DependentCareBenefits = n.GetStringValue(); } },
                { "employee", n => { Employee = n.GetObjectValue<global::Soenneker.Plaid.OpenApiClient.Models.Employee>(global::Soenneker.Plaid.OpenApiClient.Models.Employee.CreateFromDiscriminatorValue); } },
                { "employer", n => { Employer = n.GetObjectValue<global::Soenneker.Plaid.OpenApiClient.Models.PaystubEmployer>(global::Soenneker.Plaid.OpenApiClient.Models.PaystubEmployer.CreateFromDiscriminatorValue); } },
                { "employer_id_number", n => { EmployerIdNumber = n.GetStringValue(); } },
                { "federal_income_tax_withheld", n => { FederalIncomeTaxWithheld = n.GetStringValue(); } },
                { "medicare_tax_withheld", n => { MedicareTaxWithheld = n.GetStringValue(); } },
                { "medicare_wages_and_tips", n => { MedicareWagesAndTips = n.GetStringValue(); } },
                { "nonqualified_plans", n => { NonqualifiedPlans = n.GetStringValue(); } },
                { "other", n => { Other = n.GetStringValue(); } },
                { "retirement_plan", n => { RetirementPlan = n.GetStringValue(); } },
                { "social_security_tax_withheld", n => { SocialSecurityTaxWithheld = n.GetStringValue(); } },
                { "social_security_tips", n => { SocialSecurityTips = n.GetStringValue(); } },
                { "social_security_wages", n => { SocialSecurityWages = n.GetStringValue(); } },
                { "state_and_local_wages", n => { StateAndLocalWages = n.GetCollectionOfObjectValues<global::Soenneker.Plaid.OpenApiClient.Models.W2StateAndLocalWages>(global::Soenneker.Plaid.OpenApiClient.Models.W2StateAndLocalWages.CreateFromDiscriminatorValue)?.AsList(); } },
                { "statutory_employee", n => { StatutoryEmployee = n.GetStringValue(); } },
                { "tax_year", n => { TaxYear = n.GetStringValue(); } },
                { "third_party_sick_pay", n => { ThirdPartySickPay = n.GetStringValue(); } },
                { "wages_tips_other_comp", n => { WagesTipsOtherComp = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("allocated_tips", AllocatedTips);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Plaid.OpenApiClient.Models.W2Box12>("box_12", Box12);
            writer.WriteStringValue("box_9", Box9);
            writer.WriteStringValue("dependent_care_benefits", DependentCareBenefits);
            writer.WriteObjectValue<global::Soenneker.Plaid.OpenApiClient.Models.Employee>("employee", Employee);
            writer.WriteObjectValue<global::Soenneker.Plaid.OpenApiClient.Models.PaystubEmployer>("employer", Employer);
            writer.WriteStringValue("employer_id_number", EmployerIdNumber);
            writer.WriteStringValue("federal_income_tax_withheld", FederalIncomeTaxWithheld);
            writer.WriteStringValue("medicare_tax_withheld", MedicareTaxWithheld);
            writer.WriteStringValue("medicare_wages_and_tips", MedicareWagesAndTips);
            writer.WriteStringValue("nonqualified_plans", NonqualifiedPlans);
            writer.WriteStringValue("other", Other);
            writer.WriteStringValue("retirement_plan", RetirementPlan);
            writer.WriteStringValue("social_security_tax_withheld", SocialSecurityTaxWithheld);
            writer.WriteStringValue("social_security_tips", SocialSecurityTips);
            writer.WriteStringValue("social_security_wages", SocialSecurityWages);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Plaid.OpenApiClient.Models.W2StateAndLocalWages>("state_and_local_wages", StateAndLocalWages);
            writer.WriteStringValue("statutory_employee", StatutoryEmployee);
            writer.WriteStringValue("tax_year", TaxYear);
            writer.WriteStringValue("third_party_sick_pay", ThirdPartySickPay);
            writer.WriteStringValue("wages_tips_other_comp", WagesTipsOtherComp);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
