// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Plaid.OpenApiClient.Models
{
    /// <summary>An ISO-4217 currency code, used with e-wallets and transactions.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum WalletISOCurrencyCode
    {
        [EnumMember(Value = "GBP")]
        #pragma warning disable CS1591
        GBP,
        #pragma warning restore CS1591
        [EnumMember(Value = "EUR")]
        #pragma warning disable CS1591
        EUR,
        #pragma warning restore CS1591
    }
}
