// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Plaid.OpenApiClient.Models
{
    /// <summary>The warning code identifies a specific kind of warning. `OWNERS_UNAVAILABLE` indicates that account-owner information is not available.`INVESTMENTS_UNAVAILABLE` indicates that Investments specific information is not available. `TRANSACTIONS_UNAVAILABLE` indicates that transactions information associated with Credit and Depository accounts are unavailable.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum Warning_warning_code
    {
        [EnumMember(Value = "OWNERS_UNAVAILABLE")]
        #pragma warning disable CS1591
        OWNERS_UNAVAILABLE,
        #pragma warning restore CS1591
        [EnumMember(Value = "INVESTMENTS_UNAVAILABLE")]
        #pragma warning disable CS1591
        INVESTMENTS_UNAVAILABLE,
        #pragma warning restore CS1591
        [EnumMember(Value = "TRANSACTIONS_UNAVAILABLE")]
        #pragma warning disable CS1591
        TRANSACTIONS_UNAVAILABLE,
        #pragma warning restore CS1591
    }
}
