// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Plaid.OpenApiClient.Transactions.Enrich;
using Soenneker.Plaid.OpenApiClient.Transactions.Get;
using Soenneker.Plaid.OpenApiClient.Transactions.Recurring;
using Soenneker.Plaid.OpenApiClient.Transactions.Refresh;
using Soenneker.Plaid.OpenApiClient.Transactions.Sync;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Plaid.OpenApiClient.Transactions
{
    /// <summary>
    /// Builds and executes requests for operations under \transactions
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class TransactionsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The enrich property</summary>
        public global::Soenneker.Plaid.OpenApiClient.Transactions.Enrich.EnrichRequestBuilder Enrich
        {
            get => new global::Soenneker.Plaid.OpenApiClient.Transactions.Enrich.EnrichRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The getPath property</summary>
        public global::Soenneker.Plaid.OpenApiClient.Transactions.Get.GetRequestBuilder GetPath
        {
            get => new global::Soenneker.Plaid.OpenApiClient.Transactions.Get.GetRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The recurring property</summary>
        public global::Soenneker.Plaid.OpenApiClient.Transactions.Recurring.RecurringRequestBuilder Recurring
        {
            get => new global::Soenneker.Plaid.OpenApiClient.Transactions.Recurring.RecurringRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The refresh property</summary>
        public global::Soenneker.Plaid.OpenApiClient.Transactions.Refresh.RefreshRequestBuilder Refresh
        {
            get => new global::Soenneker.Plaid.OpenApiClient.Transactions.Refresh.RefreshRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The sync property</summary>
        public global::Soenneker.Plaid.OpenApiClient.Transactions.Sync.SyncRequestBuilder Sync
        {
            get => new global::Soenneker.Plaid.OpenApiClient.Transactions.Sync.SyncRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Plaid.OpenApiClient.Transactions.TransactionsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TransactionsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/transactions", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Plaid.OpenApiClient.Transactions.TransactionsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TransactionsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/transactions", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
