// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Plaid.OpenApiClient.User.Create;
using Soenneker.Plaid.OpenApiClient.User.Financial_data;
using Soenneker.Plaid.OpenApiClient.User.Get;
using Soenneker.Plaid.OpenApiClient.User.Identity;
using Soenneker.Plaid.OpenApiClient.User.Items;
using Soenneker.Plaid.OpenApiClient.User.Products;
using Soenneker.Plaid.OpenApiClient.User.Remove;
using Soenneker.Plaid.OpenApiClient.User.Third_party_token;
using Soenneker.Plaid.OpenApiClient.User.Transactions;
using Soenneker.Plaid.OpenApiClient.User.Update;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Plaid.OpenApiClient.User
{
    /// <summary>
    /// Builds and executes requests for operations under \user
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class UserRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The create property</summary>
        public global::Soenneker.Plaid.OpenApiClient.User.Create.CreateRequestBuilder Create
        {
            get => new global::Soenneker.Plaid.OpenApiClient.User.Create.CreateRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The financial_data property</summary>
        public global::Soenneker.Plaid.OpenApiClient.User.Financial_data.Financial_dataRequestBuilder Financial_data
        {
            get => new global::Soenneker.Plaid.OpenApiClient.User.Financial_data.Financial_dataRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The getPath property</summary>
        public global::Soenneker.Plaid.OpenApiClient.User.Get.GetRequestBuilder GetPath
        {
            get => new global::Soenneker.Plaid.OpenApiClient.User.Get.GetRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The identity property</summary>
        public global::Soenneker.Plaid.OpenApiClient.User.Identity.IdentityRequestBuilder Identity
        {
            get => new global::Soenneker.Plaid.OpenApiClient.User.Identity.IdentityRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The items property</summary>
        public global::Soenneker.Plaid.OpenApiClient.User.Items.ItemsRequestBuilder Items
        {
            get => new global::Soenneker.Plaid.OpenApiClient.User.Items.ItemsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The products property</summary>
        public global::Soenneker.Plaid.OpenApiClient.User.Products.ProductsRequestBuilder Products
        {
            get => new global::Soenneker.Plaid.OpenApiClient.User.Products.ProductsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The remove property</summary>
        public global::Soenneker.Plaid.OpenApiClient.User.Remove.RemoveRequestBuilder Remove
        {
            get => new global::Soenneker.Plaid.OpenApiClient.User.Remove.RemoveRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The third_party_token property</summary>
        public global::Soenneker.Plaid.OpenApiClient.User.Third_party_token.Third_party_tokenRequestBuilder Third_party_token
        {
            get => new global::Soenneker.Plaid.OpenApiClient.User.Third_party_token.Third_party_tokenRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The transactions property</summary>
        public global::Soenneker.Plaid.OpenApiClient.User.Transactions.TransactionsRequestBuilder Transactions
        {
            get => new global::Soenneker.Plaid.OpenApiClient.User.Transactions.TransactionsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The update property</summary>
        public global::Soenneker.Plaid.OpenApiClient.User.Update.UpdateRequestBuilder Update
        {
            get => new global::Soenneker.Plaid.OpenApiClient.User.Update.UpdateRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Plaid.OpenApiClient.User.UserRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public UserRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/user", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Plaid.OpenApiClient.User.UserRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public UserRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/user", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
